### ISSUE TITLE
ArgumentNullException "Value cannot be null. (Parameter 'source')" at 5/31/2024 1:59:13 AM -04:00

### ISSUE THREAD

**Issue by stanrain** [njthomson/SrvSurvey#107]
### What happened?

Just exploring business as usual. Not sure what went wrong.

### Version

1.1.0.6

### Exception message

Value cannot be null. (Parameter 'source')

### Exception stack

   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Sum[TSource,TResult,TAccumulator](IEnumerable`1 source, Func`2 selector)
   at SrvSurvey.game.Game.onJournalEntry(Cargo entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.initCargoData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1806","build":"r302447/r0 ","timestamp":"2024-05-31T05:44:06Z","event":"Fileheader"}
01:59:06: Game.initSystemData: playForwards 'FSSBodySignals' (5/31/2024 5:56:02 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:56:02 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:56:34 AM)
01:59:06: Game.initSystemData: playForwards 'FSSBodySignals' (5/31/2024 5:56:50 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:56:51 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:56:58 AM)
01:59:06: Game.initSystemData: playForwards 'FSSBodySignals' (5/31/2024 5:57:03 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:57:03 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:57:10 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:57:27 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:57:37 AM)
01:59:06: Game.initSystemData: playForwards 'Scan' (5/31/2024 5:57:43 AM)
01:59:06: Game.initSystemData: playForwards 'FSSAllBodiesFound' (5/31/2024 5:57:43 AM)
01:59:06: Game.initSystemData: complete 'Phroi Hypue YP-R b10-0' (657800698457), bodyCount: 28
01:59:06: Game.initCargoData: rewind to last Cargo
01:59:06: Game.initCargoData: Processing 2 cargo journal items forwards...
01:59:06: Game.initCargoData: cargo playForwards 'Cargo' (5/31/2024 5:46:10 AM)
01:59:06: Exception: Value cannot be null. (Parameter 'source')
01:59:06: Inner exception: 
01:59:06: Stack:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Sum[TSource,TResult,TAccumulator](IEnumerable`1 source, Func`2 selector)
   at SrvSurvey.game.Game.onJournalEntry(Cargo entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.initCargoData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

**Comment by njthomson** [comment]
Thank you @stanrain for reporting this.

Could you try again with the latest build?
https://github.com/njthomson/SrvSurvey/releases

**Comment by njthomson** [comment]
@stanrain - the code in that reported stack trace has been removed and the issue should be fixed now. Please let me know if you see anything like this again. Thank you for using and reporting issues in SrvSurvey. 

I recommend moving to this recent build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.53
