### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 12/06/2024 17:59:32 +03:00

### ISSUE THREAD

**Issue by CHARLI-ONE** [njthomson/SrvSurvey#108]
### What happened?

No working 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SrvSurvey.Util.GetBodyValue(SystemBody body, Boolean cmdrMapped, Boolean withEfficiencyBonus)
   at SrvSurvey.game.SystemData.applyMainStarHonkBonus()
   at SrvSurvey.game.SystemData.onJournalEntry(Scan entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__10_9()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()

### Version

1.1.3.34

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.Util.GetBodyValue(SystemBody body, Boolean cmdrMapped, Boolean withEfficiencyBonus)
   at SrvSurvey.game.SystemData.applyMainStarHonkBonus()
   at SrvSurvey.game.SystemData.onJournalEntry(Scan entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__10_9()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1806","build":"r302447/r0 ","timestamp":"2024-06-12T14:46:45Z","event":"Fileheader"}
17:52:41: Reading: Journal.2024-06-09T150931.01.log
17:52:41: getCommanderJournalBefore: expected cmdr: charli one, found '{ "timestamp":"2024-06-08T15:02:12Z", "event":"Commander", "FID":"F4887466", "Name":"charli one" }' from: C:\Users\User\Saved Games\Frontier Developments\Elite Dangerous\Journal.2024-06-08T175959.01.log
17:52:41: Reading: Journal.2024-06-08T175959.01.log
17:52:41: Game.initSystemData: found last FSDJump, to 'Kappa-1 Volantis' (211772499132)
17:52:41: Loading SystemData for: 'Kappa-1 Volantis' (211772499132)
17:52:41: Loaded data from: C:\Users\User\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\systems\F4887466\Kappa-1 Volantis_211772499132.json
17:52:41: walkDeep: count: 56
17:52:41: Game.initSystemData: Processing 96 journal items forwards...
17:52:41: Game.initSystemData: playForwards 'Scan' (08/06/2024 19:35:34)
17:52:41: add ring 'Kappa-1 Volantis B A Belt' to 'Kappa-2 Volantis' (2)
17:52:41: Gained: +1 436 for Scan:AutoScan of Kappa-2 Volantis
17:52:41: Game.initSystemData: playForwards 'FSSDiscoveryScan' (08/06/2024 19:35:35)
17:52:41: Game.initSystemData: playForwards 'Scan' (08/06/2024 19:35:36)
17:52:41: SystemData: add body: 'Kappa-1 Volantis B 1' (20, Unknown)
17:52:41: add ring 'Kappa-1 Volantis B 1 A Ring' to 'Kappa-1 Volantis B 1' (20)
17:52:41: add ring 'Kappa-1 Volantis B 1 B Ring' to 'Kappa-1 Volantis B 1' (20)
17:52:41: Gained: +1 200 for Scan:AutoScan of Kappa-1 Volantis B 1
17:52:41: System.NullReferenceException: Object reference not set to an instance of an object.
   at SrvSurvey.Util.GetBodyValue(SystemBody body, Boolean cmdrMapped, Boolean withEfficiencyBonus)
   at SrvSurvey.game.SystemData.applyMainStarHonkBonus()
   at SrvSurvey.game.SystemData.onJournalEntry(Scan entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__10_9()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()
17:52:41: isFirewallProblem?
System.NullReferenceException: Object reference not set to an instance of an object.
   at SrvSurvey.Util.GetBodyValue(SystemBody body, Boolean cmdrMapped, Boolean withEfficiencyBonus)
   at SrvSurvey.game.SystemData.applyMainStarHonkBonus()
   at SrvSurvey.game.SystemData.onJournalEntry(Scan entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__10_9()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()
17:52:52: Opening link: (length: 7594)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=NullReferenceException+%22Object+reference+not+set+to+an+instance+of+an+object.%22+at+12%2F06%2F2024+17%3A52%3A52+
```

**Comment by njthomson** [comment]
Thank you @CHARLI-ONE for reporting this issue. I expect to have a fix out soon.

**Comment by njthomson** [comment]
Thank you again @CHARLI-ONE - this has been fixed in the latest build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.37
