### ISSUE TITLE
Exception "Unexpected entryId: '1410100'" at 6/28/2024 7:37:55 AM -05:00

### ISSUE THREAD

**Issue by SkepticalFall** [njthomson/SrvSurvey#109]
### What happened?

FSS Scan in Asura

### Version

1.1.3.0

### Exception message

Unexpected entryId: '1410100'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromEntryId(String entryId)
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId)
   at SrvSurvey.game.Game.onJournalEntry(CodexEntry entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

**Comment by njthomson** [comment]
Thank you @SkepticalFall for reporting this - the root cause has been fixed already, but that hasn't yet been published to the App store.

**Comment by njthomson** [comment]
@SkepticalFall - at long last, the fix has been pushed to the Windows app store.
