### ISSUE TITLE
FileNotFoundException "C:\windows\system32\images\beta-background.png" at 22/11/2023 16:14:32 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#11]
### What happened?

Just arrived at Beta site on Synuefe XR-H d11-102 (Guardian ruins - 'Site 1' - Regor western limit) - clicked on the 'Ruins Map' button, and the error message popped up!

### Version

1.0.8.0

### Exception message

C:\windows\system32\images\beta-background.png

### Exception stack

   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at SrvSurvey.FormRuins.loadMap(GuardianSiteData newSite)
   at SrvSurvey.FormRuins.loadMap(String name)
   at SrvSurvey.FormRuins.comboSite_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at SrvSurvey.FormRuins.showFilteredSites(GuardianSiteData siteData)
   at SrvSurvey.FormRuins..ctor(GuardianSiteData siteData)
   at SrvSurvey.FormRuins.show(GuardianSiteData siteData)
   at SrvSurvey.Main.btnRuins_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Contact Details

qbot2@aol.com

### Relevant log output

```shell
16:10:39: Mode change Flying => CommsPanel
16:10:51: Mode change CommsPanel => Flying
16:11:17: Game.event => Music
16:12:37: EliteDangerous window focus changed: False
16:12:37: Program.hideActivePlotters: 4
16:12:40: Reading 1 ruins files from disk
16:12:40: Loaded data from: C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0\guardian\F4577557\Synuefe XR-H d11-102 1 b-ruins-1.json
16:12:40: Exception: C:\windows\system32\images\beta-background.png
16:12:40: Inner exception: 
16:12:40: Stack:    at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at SrvSurvey.FormRuins.loadMap(GuardianSiteData newSite)
   at SrvSurvey.FormRuins.loadMap(String name)
   at SrvSurvey.FormRuins.comboSite_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at SrvSurvey.FormRuins.showFilteredSites(GuardianSiteData siteData)
   at SrvSurvey.FormRuins..ctor(GuardianSiteData siteData)
   at SrvSurvey.FormRuins.show(GuardianSiteData siteData)
   at SrvSurvey.Main.btnRuins_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by D0bl0z** [comment]
I'm on the Guardian Science Corp discord - Oborax

**Comment by njthomson** [comment]
Thank you for the report.

Could you try again using this build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.0.9.3

**Comment by D0bl0z** [comment]
The new build fixed it, thanks !
