### ISSUE TITLE
Exception "Unexpected entryId: '1400102'" at 2024-07-02 11:28:11 +02:00

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#110]
### What happened?

Just jumped into a system, and when I tried to open SRV Survey, I saw this error message.

### Version

1.1.3.53

### Exception message

Unexpected entryId: '1400102'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromEntryId(String entryId)
   at SrvSurvey.PlotBioStatus.onJournalEntry(CodexEntry entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.PlotBioStatus.Journals_onJournalEntry(JournalEntry entry, Int32 index)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SrvSurvey.JournalWatcher.readEntry()
   at SrvSurvey.JournalFile.readEntries(String targetCmdr)
   at SrvSurvey.Program.crashGuard(Action func, Boolean beginInvoke)

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1806","build":"r302447/r0 ","timestamp":"2024-07-02T04:46:34Z","event":"Fileheader"}
11:26:37: Changed hasLatLong: False, has nearBody: False, nearBody matches: True
11:26:37: Mode change Flying => SuperCruising
11:26:37: Found system POI from Canonn for: Bleia Eohn NH-A b5-1
11:26:37: Program.Creating plotter: PlotSysStatus
11:26:37: Program.Showing plotter: PlotSysStatus
11:26:42: Game.event => Scan
11:26:42: SystemData: add body: 'Bleia Eohn NH-A b5-1 A Belt Cluster 3' (4, Unknown)
11:26:42: PlotSysStatus: Scan event: Bleia Eohn NH-A b5-1 A Belt Cluster 3
11:26:42: Game.event => Scan
11:26:42: SystemData: add body: 'Bleia Eohn NH-A b5-1 A Belt Cluster 1' (2, Unknown)
11:26:42: PlotSysStatus: Scan event: Bleia Eohn NH-A b5-1 A Belt Cluster 1
11:26:43: Game.event => Scan
11:26:43: add ring 'Bleia Eohn NH-A b5-1 A Belt' to 'Bleia Eohn NH-A b5-1' (0)
11:26:43: Gained: +1 205 for Scan:AutoScan of Bleia Eohn NH-A b5-1
11:26:43: PlotSysStatus: Scan event: Bleia Eohn NH-A b5-1
11:26:43: Game.event => Scan
11:26:43: SystemData: add body: 'Bleia Eohn NH-A b5-1 A Belt Cluster 2' (3, Unknown)
11:26:43: PlotSysStatus: Scan event: Bleia Eohn NH-A b5-1 A Belt Cluster 2
11:26:45: Game.event => FSSDiscoveryScan
11:26:45: PlotSysStatus: FSSDiscoveryScan event: Bleia Eohn NH-A b5-1
```

**Comment by Vic502** [comment]
The app seems like it continues to function when I close the error messages.

**Comment by njthomson** [comment]
Thank you @Vic502 for reporting this.

**Comment by njthomson** [comment]
@Vic502  - this has been fixed in recent builds. Let me know if you see it again:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.64
