### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 7/5/2024 2:12:36 AM -04:00

### ISSUE THREAD

**Issue by AirHunter47** [njthomson/SrvSurvey#111]
### What happened?

Hello friends, I've been using this awesome app for some time now but it hasn't been working since yesterday. I was playing with some of the settings in the app and after that, the app doesn't recognize when the game starts. what i believe happened is that changed the "watch journal folder". If anyone could help me get back on track, it would be great.

### Version

1.1.3.0

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.FormSettings.btnClearUnclaimed_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by njthomson** [comment]
@AirHunter47 - try replacing it with `C:\Users\<username>\Saved Games\Frontier Developments`

**Comment by njthomson** [comment]
In fact, whilst browsing for a folder, you can even paste in `%USERPROFILE%\Saved Games\Frontier Developments`

**Comment by njthomson** [comment]
I have added a reset button, though it may be a while before the App store build is updated.

Glad you were able to fix this manually.
