### ISSUE TITLE
DirectoryNotFoundException "Could not find a part of the path 'D:\code\SrvSurvey\SrvSurvey\bio-criteria'." at 2024-07-08 18:18:05 +02:00

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#114]
### What happened?

Unknown.

### Version

1.1.3.63

### Exception message

Could not find a part of the path 'D:\code\SrvSurvey\SrvSurvey\bio-criteria'.

### Exception stack

   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at BioCriteria.Criteria.readCriteria()
   at BioCriteria.Predictor.predict(SystemBody body)
   at SrvSurvey.game.SystemBody.predictSpecies()
   at SrvSurvey.game.SystemData.Load(String systemName, Int64 systemAddress, String fid)
   at SrvSurvey.game.SystemData.From(ISystemDataStarter entry, String fid, String cmdrName)
   at SrvSurvey.game.Game.setLocations(ISystemDataStarter entry)
   at SrvSurvey.game.Game.onJournalEntry(FSDJump entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

**Comment by Vic502** [comment]
Already reported. Closing this instance.

**Comment by njthomson** [comment]
@Vic502 - please give this a try:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.64
