### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 9/1/2024 22:32:07 +02:00

### ISSUE THREAD

**Issue by pseudokris** [njthomson/SrvSurvey#119]
### What happened?

I opened the game and logged in. Then I Quit to Desktop. The crash happened as the game closed.

### Version

1.1.3.120

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.game.Game.get_hidePlottersFromCombatSuits() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 425
   at SrvSurvey.PlotGuardians.get_allowPlotter() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\PlotGuardians.cs:line 89
   at SrvSurvey.PlotGuardianStatus.get_allowPlotter() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\PlotGuardianStatus.cs:line 26
   at SrvSurvey.Main.updateGuardianTexts(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 767
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 307
   at SrvSurvey.Main.removeGame() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 420
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 300
   at SrvSurvey.Main.Game_modeChanged(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 485
   at SrvSurvey.game.Game.fireUpdate(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 230
   at SrvSurvey.game.Game.fireUpdate(Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 224
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 848

### Relevant log output

```shell
22:28:39: SrvSurvey version: 1.1.3.120, isAppStoreBuild: False
22:28:39: New log file: C:\Users\Q\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240901_222839.txt
22:28:39: dataFolder: C:\Users\Q\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0
22:28:39: Removing old log file: C:\Users\Q\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240901_220734.txt
22:28:39: Loaded settings: {
  "defaultOrange": "255, 111, 0",
  "defaultOrangeDim": "95, 48, 3",
  "preferredCommander": null,
  "lastCommander": "Qo7",
  "lastFid": "F10197303",
  "watchedJournalFolder": "C:\\Users\\Q\\Saved Games\\Frontier Developments\\Elite Dangerous\\",
  "hideJournalWriteTimer": false,
  "targetLatLong": {
    "lat": 34.777386,
    "long": -110.221489
  },
  "targetLatLongActive": false,
  "fadeInDuration": 150,
  "autoShowBioSummary": true,
  "autoShowBioPlot": true,
  "autoShowPlotFSS": true,
  "autoShowPlotFSSInfo": true,
  "autoShowGuardianSummary": true,
  "autoShowRamTah": true,
  "autoShowPlotSysStatus": true,
  "autoShowPlotBioSystem": false,
  "autoShowPlotGalMap": true,
  "autoShowHumanSitesTest": false,
  "autoShowPlotJumpInfoTest": true,
  "autoShowPlotBodyInfo": true,
  "autoShowPlotBodyInfoInMap": true,
  "autoShowPlotBodyInfoInOrbit": true,
  "autoHidePlotBodyInfoInBubble": true,
  "bodyInfoBubbleSize": 200,
  "collectMatsCollectionStatsTest": false,
  "showMatsCollectionDots": true,
  "skipGasGiantDSS": true,
  "skipRingsDSS": false,
  "skipLowValueDSS": true,
  "skipLowValueAmount": 1000000,
  "hideFssLowValueAmount": 10000,
  "skipHighDistanceDSS": false,
  "skipHighDistanceDSSValue": 100000,
  "autoTrackCompBioScans": true,
  "skipAnalyzedCompBioScans": true,
  "autoRemoveTrackerOnSampling": true,
  "bioRingBucketOne": 3.0,
  "bioRingBucketTwo": 7.0,
  "bioRingBucketThree": 12.0,
  "useExternalData": true,
  "useExternalBioData": false,
  "autoLoadPriorScans": true,
  "skipPriorScansLowValue": false,
  "skipPriorScansLowValueAmount": 1000000,
  "showCanonnSignalsOnRadar": true,
  "useSmallCirclesWithCanonn": true,
  "hideMyOwnCanonnSignals": true,
  "focusGameOnStart": true,
  "focusGameOnMinimize": true,
  "enableGuardianSites": true,
  "disableRuinsMeasurementGrid": false,
  "disableAerialAlignmentGrid": false,
  "hidePlottersFromCombatSuits": true,
  "hideOverlaysFromMouse": true,
  "autoShowFlightWarnings": true,
  "highGravityWarningLevel": 1.0,
  "plotterOpacity": 60.0,
  "plotterScale": 0.0,
  "formMainLocation": "2511, 301",
  "formLogsLocation": "0, 0, 0, 0",
  "formAllRuinsLocation": "0, 0, 0, 0",
  "formRuinsLocation": "0, 0, 0, 0",
  "formBeaconsLocation": "0, 0, 0, 0",
  "formMapEditor": "0, 0, 0, 0",
  "formRamTah": "0, 0, 0, 0",
  "formGenusGuideLocation": "0, 0, 0, 0",
  "formPostProcess": "0, 0, 0, 0",
  "formBuilder": "0, 0, 0, 0",
  "formShowCodex": "0, 0, 0, 0",
  "mapShowNotes": true,
  "mapShowLegend": true,
  "blinkTigger": 134217728,
  "blinkDuration": 3000,
  "processScreenshots": false,
  "addBannerToScreenshots": true,
  "deleteScreenshotOriginal": false,
  "useGuardianAerialScreenshotsFolder": true,
  "screenshotSourceFolder": "C:\\Users\\Q\\Pictures\\Frontier Developments\\Elite Dangerous",
  "screenshotTargetFolder": "C:\\Users\\Q\\Pictures\\Frontier Developments\\Elite Dangerous\\converted",
  "rotateAndTruncateAlphaAerialScreenshots": true,
  "screenshotBannerColor": "Yellow",
  "screenshotBannerLocalTime": false,
  "aerialAltAlpha": 1200.0,
  "aerialAltBeta": 1550.0,
  "aerialAltGamma": 1600.0,
  "idxGuardianPlotter": 0,
  "migratedAlphaSiteHeading": false,
  "inferColor": "102, 255, 255",
  "inferTolerance": 25,
  "inferThreshold": 0.002,
  "dataFolder1100": true,
  "pubBioCriteria": 4,
  "pubCodexRef": 4,
  "pubDataSettlementTemplate": 33,
  "pubDataGuardian": 33,
  "lastCodexRefDownload": "2024-09-01T22:19:36.2270806+02:00",
  "keepBioPlottersVisibleEnabled": true,
  "keepBioPlottersVisibleDuration": 120,
  "formGenusFilter": 0,
  "formGenusFontSize": 1,
  "formGenusShowRingGuide": true,
  "localFloraFolder": null
}
22:28:39: Reading PlotterPositions from: C:\Users\Q\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\plotters.json
22:28:39: Program.repositionPlotters: 0, rect{X=0,Y=0,Width=0,Height=0}
22:28:39: Reading PlotterPositions from: D:\Elite\SrvSurvey\plotters.json
22:28:39: Watching folder: C:\Users\Q\Saved Games\Frontier Developments\Elite Dangerous\
22:28:39: Watching file: C:\Users\Q\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
22:28:39: isMigrationValid: True, dataFolder1100: True
22:28:39: Using settlementTemplates.json from pubData
22:28:39: Reading settlementTemplates.json: C:\Users\Q\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
22:28:39: SiteTemplate.Imported 13 templates
22:28:39: Using humanSiteTemplates.json app package
22:28:39: Reading humanSiteTemplates.json: D:\Elite\SrvSurvey\humanSiteTemplates.json
22:28:39: HumanSiteTemplate.Imported 28 templates
22:28:39: updatePubData ...
22:28:40: pubDataSettlementTemplate - local: 33, remote: 33
22:28:40: pubDataGuardian - local: 33, remote: 33
22:28:40: updatePubData - complete
22:28:40: Loaded 517 ruins, 30 beacons, 155 structures
22:28:40: CodexRef init (reset: False, last downloaded: 0.006 days ago) ...
22:28:40: loadCodexRef: reading codex/ref from disk
22:28:40: prepBioRef: reading bioRef from disk
22:28:40: prepNebulae: from disk ...
22:28:40: CodexRef init - complete
22:28:40: Main.newGame: has old game:False 
22:28:40: Game .ctor, targetCmdr: 
22:28:40: CargoFile updated: 0 items in: Ship
  
22:28:40: Reading: Journal.2024-09-01T222732.01.log
22:28:40: Game.initializeFromJournal: BEGIN  (FID:), journals.Count:1
22:28:40: Game.initializeFromJournal: END Commander:, starSystem:, systemLocation:, systemBody:, journals.Count:1
22:28:40: Mode change NoFocus => MainMenu
22:28:40: Cmdr loaded: False
22:28:40: Program.Creating plotter: PlotPulse
22:28:40: Program.Showing plotter: PlotPulse
22:28:40: migratedScannedOrganicsInEntryId: , migratedNonSystemDataOrganics: 
22:28:51: Program.CloseAllPlotters
22:29:03: Game.event => Commander
22:29:03: Game.event => Materials
22:29:04: Game.event => LoadGame
22:29:04: Game.initializeFromJournal: BEGIN  (FID:), journals.Count:4
22:29:04: Loaded data from: C:\Users\Q\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\F10197303-live.json
22:29:04: Data file not found: C:\Users\Q\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\F10197303-codex.json
22:29:04: Game.initSystemData: rewind to last FSDJump or CarrierJump
22:29:04: Reading: Journal.2024-09-01T222028.01.log
22:29:04: Game.initSystemData: last location: 'Zibal' (78620124340)
22:29:04: Reading: Journal.2024-08-31T210055.01.log
22:29:04: Reading: Journal.2024-08-30T182223.01.log
22:29:04: Reading: Journal.2024-08-29T190254.01.log
22:29:04: Game.initSystemData: found last FSDJump, to 'Zibal' (78620124340)
22:29:04: Loading SystemData for: 'Zibal' (78620124340)
22:29:04: Loaded data from: C:\Users\Q\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\systems\F10197303\Zibal_78620124340.json
22:29:04: walkDeep: count: 5
22:29:04: Game.initSystemData: Processing 11 journal items forwards...
22:29:04: Game.initSystemData: playForwards 'ApproachBody' (8/29/2024 20:39:59)
22:29:04: Game.initSystemData: playForwards 'ApproachSettlement' (8/29/2024 20:40:31)
22:29:04: Game.initSystemData: playForwards 'ApproachBody' (8/29/2024 20:49:04)
22:29:04: Game.initSystemData: playForwards 'Touchdown' (8/29/2024 20:50:51)
22:29:04: Game.initSystemData: playForwards 'Disembark' (8/29/2024 20:50:59)
22:29:04: Game.initSystemData: playForwards 'Touchdown' (8/29/2024 20:55:50)
22:29:04: Game.initSystemData: playForwards 'Disembark' (8/29/2024 20:55:54)
22:29:04: Game.initSystemData: playForwards 'ApproachBody' (8/29/2024 21:01:23)
22:29:04: Game.initSystemData: playForwards 'ApproachSettlement' (8/29/2024 21:01:47)
22:29:04: Game.initSystemData: playForwards 'ApproachSettlement' (8/30/2024 16:23:27)
22:29:04: Game.initSystemData: playForwards 'ApproachSettlement' (9/1/2024 20:23:00)
22:29:04: Game.initSystemData: complete 'Zibal' (78620124340), bodyCount: 0
22:29:04: Game.initializeFromJournal: system: 'Zibal' (id:78620124340), body: '' (id:, r: 1m)
22:29:04: Game.initializeFromJournal: END Commander:Qo7, starSystem:Zibal, systemLocation:Zibal 8 b, systemBody:, journals.Count:4
22:29:04: Mode change MainMenu => Offline
22:29:04: prepSettlements: for: 'Zibal' (78620124340), sites.Count: 0
22:29:04: this.fetchedSystemData = 'Zibal'
22:29:04: Searching Spansh for 'Zibal' (78620124340)...
22:29:04: Requesting getSystem: 78620124340
22:29:04: Searching EDSM for 'Zibal'...
22:29:04: Getting system bodies by name: Zibal
22:29:04: Searching for system POI from Canonn...
22:29:04: Requesting getSystemPoi: Zibal
22:29:04: prepNebulae: from memory ...
22:29:04: this.fetchedSystemData = 'Zibal' - complete
22:29:05: Found 28 bodies from EDSM for 'Zibal'
22:29:05: Found 28 bodies from Spansh for 'Zibal'
22:29:06: Found system POI from Canonn for: Zibal
22:29:08: Game.event => ApproachSettlement
22:29:38: Game.event => Location
22:29:38: setLocations: from Location: Zibal / Zibal 8 b (Planet)
22:29:38: Loading SystemData for: 'Zibal' (78620124340)
22:29:38: setCurrentBody by id: 27
22:29:38: Cannot find PlanetRadius from status file! Searching for last Scan event.
22:29:38: Reading: Journal.2024-09-01T222028.01.log
22:29:38: Reading: Journal.2024-08-31T210055.01.log
22:29:38: Reading: Journal.2024-08-30T182223.01.log
22:29:38: Reading: Journal.2024-08-29T190254.01.log
22:29:38: searchJournalsDeep: count: 5
22:29:38: Game.event => Music
22:29:38: Game.event => Missions
22:29:38: Missions: decodeTheRuinsMissionActive: NotStarted, decodeTheLogsMissionActive: NotStarted
22:29:38: Game.event => Loadout
22:29:38: Game.event => Music
22:29:39: Changed hasLatLong: True, has nearBody: True, nearBody matches: True
22:29:39: Mode change Offline => Docked
22:29:40: CargoFile updated: 0 items in: Ship
  
22:29:40: Game.event => Cargo
22:29:58: Mode change Docked => CommsPanel
22:30:04: Mode change CommsPanel => Docked
22:30:05: Mode change Docked => InternalPanel
22:30:13: Mode change InternalPanel => Docked
22:31:28: Mode change Docked => CommsPanel
22:31:43: Mode change CommsPanel => Docked
22:32:01: Game.event => Shutdown
22:32:01: Main.removeGame, has old game: True
22:32:01: Program.CloseAllPlotters
22:32:01: Program.Closing plotter: PlotPulse
22:32:01: Exception processing event 'Shutdown':
System.NullReferenceException: Object reference not set to an instance of an object.
   at SrvSurvey.game.Game.get_hidePlottersFromCombatSuits() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 425
   at SrvSurvey.PlotGuardians.get_allowPlotter() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\PlotGuardians.cs:line 89
   at SrvSurvey.PlotGuardianStatus.get_allowPlotter() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\PlotGuardianStatus.cs:line 26
   at SrvSurvey.Main.updateGuardianTexts(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 767
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 307
   at SrvSurvey.Main.removeGame() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 420
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 300
   at SrvSurvey.Main.Game_modeChanged(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 485
   at SrvSurvey.game.Game.fireUpdate(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 230
   at SrvSurvey.game.Game.fireUpdate(Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 224
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 848
22:32:07: Opening link: (length: 1965)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=NullReferenceException+%22Object+reference+not+set+to+an+instance+of+an+object.%22+at+9%2F1%2F2024+22%3A32%3A07+%2
```

**Comment by njthomson** [comment]
Thank you @pseudokris for reporting this. It is a new issue but one easily fixed - I'll have a build ready soon to address this.

**Comment by njthomson** [comment]
This is fixed in build `.123`:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.123

**Comment by njthomson** [comment]
@pseudokris - please let me know if this happens again.
