### ISSUE TITLE
AggregateException "One or more errors occurred. (A task was canceled.)" at 18/09/2024 22:13:31 +01:00

### ISSUE THREAD

**Issue by trampyjoe** [njthomson/SrvSurvey#121]
### What happened?

Started scanning a bio

### Version

1.1.3.143

### Exception message

One or more errors occurred. (A task was canceled.)

### Exception stack

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SrvSurvey.PlotJumpInfo.<>c__DisplayClass16_3.<initFromRoute>b__11() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\PlotJumpInfo.cs:line 177
   at SrvSurvey.Program.crashGuard(Action func, Boolean beginInvoke) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 94

**Comment by njthomson** [comment]
Thank you @trampyjoe for reporting this. Is it happening consistently?

**Comment by njthomson** [comment]
That said, I made a code change that will likely fix this. Please try out the latest from https://github.com/njthomson/SrvSurvey/releases/ and let me know if it keeps happening.

**Comment by trampyjoe** [comment]
Just happened the once, not happened since. Not sure what system I was jumping into, sorry.

**Comment by njthomson** [comment]
Np worries, thanks @trampyjoe - give this latest build a try:
https://github.com/njthomson/SrvSurvey/releases

And let me know if you spot anything else.
