### ISSUE TITLE
FormatException "String 'log' was not recognized as a valid DateTime." at 21/09/2024 07:40:02 +01:00

### ISSUE THREAD

**Issue by Tichro** [njthomson/SrvSurvey#123]
### What happened?

Loaded the latest version, clicked the Scan all old journal files, and this happened.

### Version

1.1.3.178

### Exception message

String 'log' was not recognized as a valid DateTime.

### Exception stack

   at System.DateTimeParse.ParseExact(ReadOnlySpan`1 s, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, DateTimeStyles style, TimeSpan& offset)
   at System.DateTimeOffset.ParseExact(String input, String format, IFormatProvider formatProvider, DateTimeStyles styles)
   at System.DateTimeOffset.ParseExact(String input, String format, IFormatProvider formatProvider)
   at SrvSurvey.FormPostProcess.getTimeFromFilepath(String filepath) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormPostProcess.cs:line 149
   at SrvSurvey.FormPostProcess.<>c__DisplayClass21_0.<postProcessJournals>b__1(String filepath) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormPostProcess.cs:line 168
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at SrvSurvey.FormPostProcess.postProcessJournals() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormPostProcess.cs:line 167
   at SrvSurvey.FormPostProcess.<btnStart_Click>b__18_2() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormPostProcess.cs:line 122
   at SrvSurvey.Program.crashGuard(Action func, Boolean beginInvoke) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 83

**Comment by Tichro** [comment]
Forgot to mention that I clicked on the "set beginning of time" button on the Journal processor section first, then clicked begin.

**Comment by njthomson** [comment]
Thank you @Tichro  for reporting this. Let me see what I can do.

**Comment by Tichro** [comment]
Nice one, thank you.
Planning on getting back out there and this tool is now an essential one for me.

**Comment by njthomson** [comment]
The fix is present in this build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.184

Thank you @Tichro for your support :)

**Comment by Tichro** [comment]
Works perfectly, thanks.
