### ISSUE TITLE
Exception "Unexpected variantName: '$Codex_Ent_Thargoid_Tower_Name;' (speciesName: '$Codex_Ent_Thargoid_Tower_')" at 2024-09-29 16:11:21 +02:00

### ISSUE THREAD

**Issue by pseudokris** [njthomson/SrvSurvey#124]
### What happened?

Importing old journal files for the Codex Bingo. I wonder if it has to do with the fact I have 2 CMDRs with journal files in the same directory.

### Version

1.1.3.186

### Exception message

Unexpected variantName: '$Codex_Ent_Thargoid_Tower_Name;' (speciesName: '$Codex_Ent_Thargoid_Tower_')

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromVariant(String variantName) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 225
   at SrvSurvey.game.SystemData.onJournalEntry(ScanOrganic entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 995
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 561
   at SrvSurvey.FormPostProcess.postProcessJournals() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormPostProcess.cs:line 359
   at SrvSurvey.FormPostProcess.<btnStart_Click>b__18_2() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormPostProcess.cs:line 122
   at SrvSurvey.Program.crashGuard(Action func, Boolean beginInvoke) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 83

**Comment by njthomson** [comment]
Thank you @pseudokris for reporting this - I hope to fix out shortly.

**Comment by njthomson** [comment]
@pseudokris - give this build a try:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.200

**Comment by njthomson** [comment]
Give me a shout if you see any similar problems.
