### ISSUE TITLE
ArgumentOutOfRangeException "Specified argument was out of the range of valid values. (Parameter 'index')" at 5-10-2024 15:35:39 +02:00

### ISSUE THREAD

**Issue by S-K-Tiger** [njthomson/SrvSurvey#125]
### What happened?

Closing the "Codex Bingo" screen.

### Version

1.1.3.210

### Exception message

Specified argument was out of the range of valid values. (Parameter 'index')

### Exception stack

   at System.Windows.Forms.TreeNodeCollection.get_Item(Int32 index)
   at SrvSurvey.FormCodexBingo.tree_DrawNode(Object sender, DrawTreeNodeEventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormCodexBingo.cs:line 601
   at System.Windows.Forms.TreeView.CustomDraw(Message& m)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
15:34:01: Mode change OnFoot => Landed
15:34:11: Game.event => Music
15:34:11: Mode change Landed => MainMenu
15:34:11: Program.Closing plotter: PlotBioStatus
15:34:11: Program.Closing plotter: PlotGrounded
15:34:11: Program.Closing plotter: PlotTrackers
15:34:11: Program.CloseAllPlotters
15:34:11: Program.Closing plotter: PlotBioSystem
15:34:19: Game.event => Shutdown
15:34:19: Main.removeGame, has old game: True
15:34:19: Program.CloseAllPlotters
15:34:19: Main.Shutdown: Commander:
15:34:19: Main.removeGame, has old game: False
15:34:19: Program.CloseAllPlotters
15:34:28: Loading completions for: Vicar Tineamica (F7026584)
15:34:28: loadCodexRef: reading codex/ref from disk
15:34:28: Nodes ready
15:35:14: Exception: Specified argument was out of the range of valid values. (Parameter 'index')
15:35:14: Inner exception: 
15:35:14: Stack:    at System.Windows.Forms.TreeNodeCollection.get_Item(Int32 index)
   at SrvSurvey.FormCodexBingo.tree_DrawNode(Object sender, DrawTreeNodeEventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormCodexBingo.cs:line 601
   at System.Windows.Forms.TreeView.CustomDraw(Message& m)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by njthomson** [comment]
Thank you @S-K-Tiger for reporting this.

**Comment by njthomson** [comment]
Fix is in this build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.222
