### ISSUE TITLE
InvalidOperationException "Collection was modified; enumeration operation may not execute." at 05. Okt.. 2024 19:26:42 Uhr +02:00

### ISSUE THREAD

**Issue by Imotheb** [njthomson/SrvSurvey#126]
### What happened?

I startet the new version

### Version

1.1.3.210

### Exception message

Collection was modified; enumeration operation may not execute.System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at BioCriterias.BioCriteria.readCriteria() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\BioCriteria.cs:line 73
   at BioCriterias.BioPredictor.predict(SystemBody body) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\BioPredictor.cs:line 18
   at SrvSurvey.game.SystemBody.predictSpecies() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 2190
   at SrvSurvey.game.Game.<>c__DisplayClass142_0.<deferPredictSpecies>b__1() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 1107
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

### Exception stack

   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at BioCriterias.BioCriteria.readCriteria() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\BioCriteria.cs:line 73
   at BioCriterias.BioPredictor.predict(SystemBody body) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\BioPredictor.cs:line 18
   at SrvSurvey.game.SystemBody.predictSpecies() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 2190
   at SrvSurvey.game.Game.<>c__DisplayClass142_0.<deferPredictSpecies>b__1() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 1107
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1809","build":"r305601/r0 ","timestamp":"2024-10-05T15:53:20Z","event":"Fileheader"}
19:26:23: prepNebulae: from memory ...
19:26:23: this.fetchedSystemData = 'Wolf 1182' - complete
19:26:23: Game.initializeFromJournal: system: 'Wolf 1182' (id:1075612485995), body: '' (id:, r: 1m)
19:26:23: Game.initializeFromJournal: END Commander:Imotheb, starSystem:Wolf 1182, systemLocation:Wolf 1182 A, systemBody:, journals.Count:323
19:26:23: Mode change NoFocus => SuperCruising
19:26:23: Cmdr loaded: True
19:26:23: predictSpecies: 'Wolf 1182 B 6 a'...
19:26:23: predictSpecies: 'Wolf 1182 B 6 a'...
19:26:23: predictSpecies: 'Wolf 1182 B 6 a'...
19:26:23: Exception: Collection was modified; enumeration operation may not execute.
19:26:23: Inner exception: 
19:26:23: Stack:    at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at BioCriterias.BioCriteria.readCriteria() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\BioCriteria.cs:line 73
   at BioCriterias.BioPredictor.predict(SystemBody body) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\BioPredictor.cs:line 18
   at SrvSurvey.game.SystemBody.predictSpecies() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 2190
   at SrvSurvey.game.Game.<>c__DisplayClass142_0.<deferPredictSpecies>b__1() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 1107
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
19:26:23: Wolf 1182 B: 516 vs Wolf 1182 A: 489,90909090909093 => 0,9494362226920366
19:26:23: predictSpecies: 'Wolf 1182 B 6 a' predicted 3 rewards: 1 M
19:26:23: 
> Bacterium Vesicula - Orange (2320503)
> Fonticulua Campestris - Teal (2370205)
> Fonticulua Campestris - Amethyst (2370207)
19:26:23: Loaded data from: C:\Users\Server\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\F1260387-codex-18.json
19:26:23: Found 27 bodies from EDSM for 'Wolf 1182'
19:26:23: Found 0 stations from Canonn in: Wolf 1182
19:26:24: Found system POI from Canonn for: Wolf 1182
19:26:24: Found 27 bodies from Spansh for 'Wolf 1182'
```

**Comment by njthomson** [comment]
Thank you @Imotheb for sharing.

**Comment by njthomson** [comment]
@Imotheb - does this happen every time? Or only on some occasions?

**Comment by Imotheb** [comment]
Only once it happend.
O7

njthomson ***@***.***> schrieb am Mo., 7. Okt. 2024, 02:20:

**Comment by njthomson** [comment]
I reworked some start up tasks yesterday, so I suspect this will be naturally fixed with that.

**Comment by Imotheb** [comment]
Very good. It's here 04:30 I must drive to my work. I will test it later.
When iam back.
O7

njthomson ***@***.***> schrieb am Mo., 7. Okt. 2024, 04:18:

**Comment by njthomson** [comment]
When chance allows, this is the build to try:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.222

**Comment by njthomson** [comment]
@Imotheb - give me a shout if you see anything like this again.
