### ISSUE TITLE
Win32Exception "An error occurred trying to start process 'C:\Users\Server\Pictures\Frontier Developments\Elite Dangerous\converted' with working directory 'D:\Downloads\Elitze Dangerous\Ed Connectot\SrvSurvey'. Das System kann die angegebene Datei nicht finden." at 01. Nov.. 2024 01:45:55 Uhr +01:00

### ISSUE THREAD

**Issue by Imotheb** [njthomson/SrvSurvey#139]
### What happened?

I would see into the folder to see that it convertet the screens corectly

![image](https://github.com/user-attachments/assets/3d705a29-2e6d-43d8-acee-017616886174)

### Version

2.0.2.27

### Exception message

An error occurred trying to start process 'C:\Users\Server\Pictures\Frontier Developments\Elite Dangerous\converted' with working directory 'D:\Downloads\Elitze Dangerous\Ed Connectot\SrvSurvey'. Das System kann die angegebene Datei nicht finden.

### Exception stack

   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SrvSurvey.Util.openLink(String link) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Util.cs:line 139
   at SrvSurvey.FormSettings.linkScreenshotFolder_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormSettings.cs:line 372
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by njthomson** [comment]
Good find @Imotheb. I take it the folder `C:\Users\Server\Pictures\Frontier Developments\Elite Dangerous\converted` does exist?

**Comment by njthomson** [comment]
@Imotheb - this should be fixed in this build, let me know if it gives you more grief:
https://github.com/njthomson/SrvSurvey/releases/tag/2.0.2.40
