### ISSUE TITLE
InvalidOperationException "Collection was modified; enumeration operation may not execute." at 01/11/2024 14:29:03 +01:00

### ISSUE THREAD

**Issue by InvestigateXM** [njthomson/SrvSurvey#140]
### What happened?

FSSing a System I believe, but not entirely sure when this error happened as I didn't discover it instantly

### Version

2.0.2.32

### Exception message

Collection was modified; enumeration operation may not execute.

### Exception stack

   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at SrvSurvey.game.Data.Save()
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1900","build":"r307202/r0 ","timestamp":"2024-11-01T10:09:38Z","event":"Fileheader"}
14:25:31: Program.Closing plotter: PlotJumpInfo
14:25:44: Mode change SuperCruising => InternalPanel
14:25:44: Program.Closing plotter: PlotSysStatus
14:25:47: Mode change InternalPanel => SuperCruising
14:25:47: Program.Creating plotter: PlotSysStatus
14:25:47: Program.Showing plotter: PlotSysStatus
14:26:11: Program.Creating plotter: PlotJumpInfo
14:26:11: Program.Showing plotter: PlotJumpInfo
14:26:45: Program.Closing plotter: PlotJumpInfo
14:27:06: Mode change SuperCruising => FSS
14:27:06: Program.Creating plotter: PlotFSS
14:27:06: Program.Showing plotter: PlotFSS
14:27:06: Program.Creating plotter: PlotFSSInfo
14:27:06: Program.Showing plotter: PlotFSSInfo
14:27:49: Mode change FSS => SuperCruising
14:27:49: Program.Closing plotter: PlotFSS
14:27:49: Stop watching FSS pixels
14:27:49: Program.Closing plotter: PlotFSSInfo
14:27:52: Program.Creating plotter: PlotJumpInfo
14:27:52: Program.Showing plotter: PlotJumpInfo
```

**Comment by njthomson** [comment]
Thank you @InvestigateXM for reporting this. This one is going to be a tricky one to pin down.

Would you be willing to share the whole log file? They can be found in `%appdata%\SrvSurvey\SrvSurvey\1.1.0.0\logs`

**Comment by InvestigateXM** [comment]
[srvs-20241101_134111.txt](https://github.com/user-attachments/files/17602647/srvs-20241101_134111.txt)

I think this is the one from the initial report, it did happen a second time a bit later with the following log:

[srvs-20241101_142946.txt](https://github.com/user-attachments/files/17602660/srvs-20241101_142946.txt)

**Comment by njthomson** [comment]
The next release will have a fix. You can get early access from the bottom of this page:
https://github.com/njthomson/SrvSurvey/actions/runs/11638841481

**Comment by njthomson** [comment]
@InvestigateXM  - this is that next build:
https://github.com/njthomson/SrvSurvey/releases/tag/2.0.2.37

**Comment by InvestigateXM** [comment]
Thanks, will try it out once Exploration data can be handed in for Powerplay again and I have a reason to go out into the black again :)

**Comment by njthomson** [comment]
@InvestigateXM - this was a general class of problem that kept popping up for a while. I added a bunch of small fixes any time I saw this, and it has happened in a while now.

I'm going to close this out, but please re-activate or give me a shout if you see it again.
