### ISSUE TITLE
InvalidOperationException "Collection was modified; enumeration operation may not execute." at 10/11/2024 23:17:30 +00:00

### ISSUE THREAD

**Issue by rah99** [njthomson/SrvSurvey#146]
### What happened?

Jumping from one system to another.

### Version

2.0.2.0

### Exception message

Collection was modified; enumeration operation may not execute.

### Exception stack

   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at SrvSurvey.game.Data.Save()
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

**Comment by rah99** [comment]
It could have happened before whilst I was doing an FSS, as I noticed the jump tracker overlay did not change so clicked on the app and it pinged, leading to this bug report.

**Comment by njthomson** [comment]
Thank you @rah99 for reporting this - this has been an elusive bug to solve and there's fresh info above.

**Comment by njthomson** [comment]
This has been fixed, but it has not yet been published to the Microsoft App store.

**Comment by rah99** [comment]
Thanks @njthomson, I will download it from the repo - soz to keep on finding bugs - hey I know the feeling - grrrr - hehehe

**Comment by njthomson** [comment]
@rah99 let me know if SrvSurvey gives you any more grief.
