### ISSUE TITLE
Exception "Unexpected entryId: '24507'" at 11/14/2024 8:21:40 PM -05:00

### ISSUE THREAD

**Issue by Rythillian** [njthomson/SrvSurvey#147]
### What happened?

Was revisiting old systems from a journey in 2022. Had looked through my logs to find systems that might have missed bio signals and created a list of bookmarks. Everything was working fine until I loaded into this particular system and it caused the program to crash. Closing any other programs that are monitoring the logs will still result in the crash, relaunching the game and program also still results in a crash.

### Version

2.0.2.43

### Exception message

Unexpected entryId: '24507'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromEntryId(String entryId, Boolean allowNull)
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId)
   at SrvSurvey.game.SystemOrganism.lookupMissingNamesIfNeeded()
   at SrvSurvey.game.SystemBody.predictSpecies()
   at SrvSurvey.game.Game.predictSystemSpecies()
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__12_9()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__12_2()

**Comment by njthomson** [comment]
Thank you @Rythillian for reporting this. Let me look at the code, but I suspect I'll be asking to see a copy of .json file on your system. Let me get back to you.

**Comment by njthomson** [comment]
@Rythillian - at long last I think I have figured this out. Do you happen to remember the system you were in at the time?

I have a fix ready, but I would like to confirm it in a system known to have this problem.

**Comment by Rythillian** [comment]
> [@Rythillian](https://github.com/Rythillian) - at long last I think I have figured this out. Do you happen to remember the system you were in at the time?
> 
> I have a fix ready, but I would like to confirm it in a system known to have this problem.

I'll have to login and check but it's likely I still have all the log files! So I can pinpoint the system probably. I'll message you here with the system name when I get the chance (doing some work atm as I write this lol).

**Comment by njthomson** [comment]
I'm going to close this out this old issue. A code change was made to help here, but let me know if you return to that system and/or you see anything like this again.
