### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 11/18/2024 6:15:55 AM -04:00

### ISSUE THREAD

**Issue by mrknify** [njthomson/SrvSurvey#150]
### What happened?

don't actually know. during transfer of cargo, I went a bit fast and it switched from cargo tab to my carrier switch ship section while I was prepping to transfer cargo. (rare cargo)

### Version

2.0.2.0

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.RouteInfo.<>c__DisplayClass17_2.<lookupSystem>b__5()
   at SrvSurvey.Program.crashGuard(Action func, Boolean beginInvoke)

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1900","build":"r307202/r0 ","timestamp":"2024-11-18T09:27:32Z","event":"Fileheader"}
06:14:08: Program.Showing plotter: PlotSysStatus
06:14:11: Game.event => DockingRequested
06:14:12: Game.event => DockingGranted
06:14:12: Mode change ExternalPanel => Flying
06:14:12: Program.Closing plotter: PlotSysStatus
06:14:14: Game.event => Music
06:14:44: Game.event => Docked
06:14:44: setMarketId: 3705417984
06:14:44: Game.event => Music
06:14:44: Mode change Flying => Docked
06:15:02: Mode change Docked => StationServices
06:15:04: Mode change StationServices => InternalPanel
06:15:08: Mode change InternalPanel => StationServices
06:15:11: Mode change StationServices => Docked
06:15:12: Mode change Docked => InternalPanel
06:15:31: Game.event => CargoTransfer
06:15:31: Updating inventory from transfer
06:15:31: Game.CargoTransfer: Current cargo:
  nanomedicines: 0
  hiporganophosphates: 0
  rajukrustoves: 0
06:15:34: CargoFile updated: 0 items in: Ship
  
06:15:34: Game.event => Cargo
```

**Comment by njthomson** [comment]
Thank you @mrknify for reporting this ... let me see what I can find.

**Comment by njthomson** [comment]
Whilst not yet published to the Windows app store, the code that had the error has since been removed (and reworked into something else).

**Comment by njthomson** [comment]
@mrknify - the latest build is now available in the Windows App store:
https://www.microsoft.com/store/productId/9NGT6RRH6B7N

I'm going to close this out but please give me a shout if you see anything like it again.

**Comment by mrknify** [comment]
Awesome! I'll update as soon as I get back on!
