### ISSUE TITLE
Exception "New site found??" at 19/11/2024 11:21:30 -03:00

### ISSUE THREAD

**Issue by GALDART** [njthomson/SrvSurvey#151]
### What happened?

crashes when sending the Fleet Carrier to jump

### Version

2.0.2.42

### Exception message

New site found??

### Exception stack

   at SrvSurvey.game.SystemSettlementSummary.forRuins(SystemData systemData, SystemBody body, Int32 idx) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\GuardianSiteData.cs:line 1257
   at SrvSurvey.game.SystemData.prepSettlements() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 1513
   at SrvSurvey.game.SystemData.get_settlements() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 1494
   at SrvSurvey.PlotGuardianSystem.get_allowPlotter() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\plotters\PlotGuardianSystem.cs:line 10
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 379
   at SrvSurvey.Main.Game_modeChanged(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 513
   at SrvSurvey.game.Game.fireUpdate(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 240
   at SrvSurvey.game.Game.checkModeChange() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 273
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 644
   at SrvSurvey.game.Game.onJournalEntry(LoadGame entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 938
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(IJournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 904

### Relevant log output

```shell
{"part":1,"language":"Portuguese/BR","Odyssey":true,"gameversion":"4.0.0.1900","build":"r307202/r0 ","timestamp":"2024-11-19T14:12:23Z","event":"Fileheader"}
11:17:59: Program.Creating plotter: PlotBioSystem
11:17:59: Program.Showing plotter: PlotBioSystem
11:17:59: Program.Creating plotter: PlotGuardianSystem
11:17:59: Program.Showing plotter: PlotGuardianSystem
11:18:03: Mode change ExternalPanel => SystemMap
11:18:11: Mode change SystemMap => StationServices
11:18:11: Program.Closing plotter: PlotBioSystem
11:18:12: Program.Closing plotter: PlotGuardianSystem
11:18:12: Program.Closing plotter: PlotSysStatus
11:18:13: Mode change StationServices => Docked
11:18:15: Mode change Docked => StationServices
11:18:26: Mode change StationServices => GalaxyMap
11:18:29: Program.Creating plotter: PlotGalMap
11:18:29: Program.Showing plotter: PlotGalMap
11:18:30: Getting system bodies by name: 2MASS J10444160-5947046
11:18:30: Getting system bodies by name: 2MASS J10444160-5947046
11:18:30: Requesting Spansh api/dump/115368495739
11:18:30: Requesting Spansh api/system/115368495739
11:18:39: Mode change GalaxyMap => StationServices
11:18:39: Program.Closing plotter: PlotGalMap
```

**Comment by njthomson** [comment]
Eek. With every jump @GALDART ? Let me see what I can do to fix this.

**Comment by njthomson** [comment]
@GALDART - do you recall what system this was in? Or were you near where Guardian sites would be expected?

**Comment by njthomson** [comment]
A fix for this has been submitted:
https://github.com/njthomson/SrvSurvey/releases/tag/2.0.2.61
