### ISSUE TITLE
Exception "New site found??" at 11/22/2024 2:02:00 PM -07:00

### ISSUE THREAD

**Issue by Bi11T** [njthomson/SrvSurvey#152]
### What happened?

Don't know. Just got the Oops notification when starting app

### Version

2.0.2.48

### Exception message

New site found??

### Exception stack

   at SrvSurvey.game.SystemSettlementSummary.forRuins(SystemData systemData, SystemBody body, Int32 idx)
   at SrvSurvey.game.SystemData.prepSettlements()
   at SrvSurvey.game.SystemData.get_settlements()
   at SrvSurvey.plotters.PlotGuardianSystem.get_allowPlotter()
   at SrvSurvey.plotters.PlotBodyInfo.get_allowPlotter()
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<afterMainLoad>b__13_8()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<afterMainLoad>b__13_1()

**Comment by njthomson** [comment]
Thanks @Bi11T for reporting this. By any chance had you been jumping using a Fleet Carrier?

**Comment by njthomson** [comment]
A fix has been submitted:
https://github.com/njthomson/SrvSurvey/releases/tag/2.0.2.61
