### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 12/28/2024 5:53:07 AM -05:00

### ISSUE THREAD

**Issue by AirHunter47** [njthomson/SrvSurvey#158]
### What happened?

I do not know what happened, I simply closed the game this popped up. The only reason why I'm reporting this is because this could be useful for you guys.

### Version

2.0.2.0

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.PlotFSSInfo.onJournalEntry(Scan entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.PlotBase.Journals_onJournalEntry(JournalEntry entry, Int32 index)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SrvSurvey.JournalWatcher.readEntry()
   at SrvSurvey.JournalFile.readEntries(String targetCmdr)
   at SrvSurvey.Program.crashGuard(Action func, Boolean beginInvoke)

**Comment by njthomson** [comment]
Thank you @AirHunter47 for reporting this, looks like the shutdown code paths are missing something.

**Comment by AirHunter47** [comment]
Understood, is there something I need to do? In the last session, I had In elite. There were no issues.

**Comment by njthomson** [comment]
Unless it happens regularly - no further action is needed. Otherwise, could you share the whole log file if it happens again.

**Comment by AirHunter47** [comment]
Awesome, I will make sure to share reports if any more issues pop up.
