### ISSUE TITLE
Srv Survey Crash

### ISSUE THREAD

**Issue by ClaudiusAetius** [njthomson/SrvSurvey#159]
### What happened?

![Screenshot 2024-12-30 191413](https://github.com/user-attachments/assets/8bf5532d-444c-4a9f-891f-8e2b679cb4ba)

### Version

2.0.2.0

### Exception message

![Screenshot 2024-12-30 191413](https://github.com/user-attachments/assets/2809c44d-8871-473f-b9ea-bbac0be2d0ef)

### Exception stack

![Screenshot 2024-12-30 191413](https://github.com/user-attachments/assets/14639757-fef4-4650-8c9e-c10ba7fcb141)

**Comment by njthomson** [comment]
Thank you @ClaudiusAetius for reporting this issue, it appears something went wrong when SrvSurvey was initializing itself on first run. Had you run SrvSurvey successfully before?

I can help get you up and running but I've question for you first: do you have the following folder? `%appdata%\SrvSurvey\SrvSurvey\1.1.0.0\`

If you do not, could you try creating it, then start SrvSurvey again.

**Comment by ClaudiusAetius** [comment]
Thanks for the reply, yes the first time I run the app it open ok but I was not with Elite Dangerous open
When I tried to open both at the same time. SRV Survey repored that problem.
I'll try to create de folder and I tell you later if the app is ok?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ClaudiusAetius** [comment]
Sorry, I added the folder in username/appdata/local/
But the same crash happened again.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by njthomson** [comment]
Righty ho. The next step will be to check/remove a hidden folder. Let me check the code and get back to you.

**Comment by ClaudiusAetius** [comment]
Ok thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by njthomson** [comment]
@ClaudiusAetius - the next step is (with SrvSurvey not running) remove folders:

`C:\Users\<USER>\AppData\Local\Packages/35333NosmohtSoftware.142860789C73F_p4c193bsm1z5a/LocalCache/Roaming/SrvSurvey/SrvSurvey`

`C:\Users\<USER>\AppData\Local\Packages/35333NosmohtSoftware.142860789C73F_p4c193bsm1z5a/LocalCache/Roaming/SrvSurvey/SrvSurvey-`

It's okay if one or both are not present.

Also make sure this folder **does** exist (it's okay being empty):
`C:\Users\<USER>\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0`

Then restart SrvSurvey and let me know what happens.

**Comment by ClaudiusAetius** [comment]
Many thanks, I'll remove the folders and test the app. I give you feedback asap.

________________________________

**Comment by ClaudiusAetius** [comment]
Sorry, just to clarify I need to remove only the two folders inside the (...) Roaming/SrvSurvey/, correct?



________________________________

**Comment by njthomson** [comment]
Under `...\Packages/35333NosmohtSoftware.142860789C73F_p4c193bsm1z5a/LocalCache\...` yes

**Comment by ClaudiusAetius** [comment]
I removed the 2 folders and the app is back on.

I appreciate your dedication and patience in helping me fix this problem.

Thank you very much.







________________________________

**Comment by njthomson** [comment]
Outstanding! I am relieved it is working again. Thank you for reaching out and your patience.

Please do not hesitate to contact me if it misbehaves again.

**Comment by ClaudiusAetius** [comment]
I'm so sorry but when I tried to open the app together with Elite Dangerous the problem happened again.

I downloaded the app from Microsoft Store. Should I remove it and install it using your Github files?

I assume this problem seems related to my game somehow but alas I'm not specialist.








________________________________

**Comment by ClaudiusAetius** [comment]
Ok here want's happened: I tried to open the app AFTER I opened ED and the app crashed.
Then I went to the "package" forlder and saw SrvSurvey created again the 2 folders I deleted before.
I deleted the folder again and try to open the app white ED were still open and works.

It seems the app creates those 2 folders automatically. I need to delete then every time I open it...



________________________________

**Comment by njthomson** [comment]
The short answer is using the GitHub build will not have these problems.

I'd love to see a log file from SrvSurvey - if you see any.

The long answer is:

- The code wants to use `%appdata%\SrvSurvey\SrvSurvey` but in Windows store apps that gets silent redirected to the longer folder.
- This is a problem because uninstalling the app means you lose all your survey data.
- However, if the initial folder exists the silent redirection will not occur.
- So I try to make the app move any existing data from one folder to the other, but I cannot refer to the initial folder directly in code as that would be redirected.
- The folder name ending with - is an attempt to confuse windows to break that redirection.


Hmm, are you running on Windows 11?

**Comment by ClaudiusAetius** [comment]
Hi

Yeah I'm using the last version of Win 11. Earlier you asked me if I could send you the app log. I don't know how to find it, but if you could tell me where it is I can send you.

________________________________

**Comment by njthomson** [comment]
In any of the folders above, look for a child folder `logs`. Any of the files in there would be useful.

**Comment by MAKE62-art** [comment]
SRV Survey work perfect, then crashed. And not working at all. I try uninstalling and new install, nothing.

Here read:
System.NullReferenceException: Object reference not set to an instance of an object.
at SrvSurvey.Main..ctor()
at SrvSurvey.program.Main(String[] args)

**Comment by njthomson** [comment]
@ClaudiusAetius - did SrvSurvey ever start working for you?

**Comment by ClaudiusAetius** [comment]
Sorry the late response, yes, it's ok now thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Inhumierer** [comment]
FYI: Had the same issue today, German Win 11, latest official updates as today. EXE installer from ZIP file works.
And btw: outstanding tool, thanks!

**Comment by njthomson** [comment]
@Inhumierer - you got something like this?

![Image](https://github.com/user-attachments/assets/3c5fab62-9167-4406-aeb4-4404a37ae4bc)

**Comment by Inhumierer** [comment]
Yes, but error message in German. Tnx 4 caring. But as I wrote, no worries, EXE installer fronm GIT worked perfect.

**Comment by Vakiwey** [comment]
<img width="407" height="281" alt="Image" src="https://github.com/user-attachments/assets/8440b9b3-c211-4f89-8104-19dbcdd97e03" />
And the file plotter.json doesnt exist

**Comment by njthomson** [comment]
@Vakiwey - try my suggestions from this issue: https://github.com/njthomson/SrvSurvey/issues/343

Give me an @ if it keeps giving you grief.
