### ISSUE TITLE
Exception "BioRef is not loaded." at 12/12/2023 17:09:19 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#16]
### What happened?

Elite already running 
clicked on the SrvSurvey.exe 
the error report appeared
Srv Survey window opens, and reports that the game is not active

### Version

1.0.0.0+398712a14dabf6741affee7b2dce4e47f451024e

### Exception message

BioRef is not loaded.

### Exception stack

   at SrvSurvey.canonn.CodexRef.genusFromEntryId(String entryId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 210
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 204
   at SrvSurvey.game.SystemData.onJournalEntry(CodexEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 322
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 180
   at SrvSurvey.game.Game.initSystemData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 628
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 473
   at SrvSurvey.game.Game..ctor(String cmdr) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 135
   at SrvSurvey.Main.newGame() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 196
   at SrvSurvey.Main.Main_Load(Object sender, EventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 106
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
17:07:56: Game.initSystemData: playForwards 'FSSDiscoveryScan' (12/12/2023 16:42:52)
17:07:56: Game.initSystemData: playForwards 'SAAScanComplete' (12/12/2023 17:02:25)
17:07:56: Game.initSystemData: playForwards 'SAASignalsFound' (12/12/2023 17:02:25)
17:07:56: add organism 'Brain Trees' to 'Wregoe BE-T d3-58 B 1' (10)
17:07:56: Game.initSystemData: playForwards 'Scan' (12/12/2023 17:02:26)
17:07:56: Game.initSystemData: playForwards 'ApproachBody' (12/12/2023 17:03:13)
17:07:56: Game.initSystemData: playForwards 'CodexEntry' (12/12/2023 17:05:39)
17:07:56: Exception: BioRef is not loaded.
17:07:56: Inner exception: 
17:07:56: Stack:    at SrvSurvey.canonn.CodexRef.genusFromEntryId(String entryId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 210
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 204
   at SrvSurvey.game.SystemData.onJournalEntry(CodexEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 322
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 180
   at SrvSurvey.game.Game.initSystemData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 628
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 473
   at SrvSurvey.game.Game..ctor(String cmdr) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 135
   at SrvSurvey.Main.newGame() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 196
   at SrvSurvey.Main.Main_Load(Object sender, EventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 106
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by njthomson** [comment]
Thank you @D0bl0z for reporting this, it should be fixed in the next build. Please give it another try with that.

**Comment by njthomson** [comment]
This should be fixed in the latest build.
