### ISSUE TITLE
Exception "BioRef is not loaded." at 13/12/2023 09:37:17 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#17]
### What happened?

Downloaded the SrvSurvey-1.0.9.24.zip file from github
extracted the files to a folder named     SrvSurvey-1.0.9.24
Attempted to run the program by clicking on the SrvSurvey.exe file
The Oops error window popped up

### Version

1.0.0.0+57de5e0138ce854a1ef31e031ead622556d0548a

### Exception message

BioRef is not loaded.

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromEntryId(String entryId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 211
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 205
   at SrvSurvey.game.SystemData.onJournalEntry(CodexEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 590
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 448
   at SrvSurvey.game.Game.initSystemData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 628
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 473
   at SrvSurvey.game.Game..ctor(String cmdr) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 135
   at SrvSurvey.Main.newGame() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 198
   at SrvSurvey.Main.Main_Load(Object sender, EventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 106
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Contact Details

qbot2@aol.com

### Relevant log output

```shell
09:35:32: !
09:35:32: !
09:35:32: !
09:35:32: !
09:35:32: !
09:35:32: !
09:35:32: !
09:35:32: !
09:35:32: !
09:35:32: !
```

**Comment by njthomson** [comment]
This should be fixed in the latest build.
