### ISSUE TITLE
ArgumentException "Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')" at 14/12/2023 22:40:13 +00:00

### ISSUE THREAD

**Issue by brammmers** [njthomson/SrvSurvey#18]
### What happened?

opened new build, loaded game from save into Solo mode

### Version

1.0.0.0+0b7ffd287e7193e796d545208d8cd72b260e1983

### Exception message

Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')

### Exception stack

   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at SrvSurvey.game.SystemData.getDssRemainingNames()
   at SrvSurvey.PlotSysStatus.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
22:39:15: SystemData: add body: 'Hypio Pri BS-H d11-9188 A 4 a' (46, Unknown)
22:39:15: SystemData: add body: 'Hypio Pri BS-H d11-9188 B 1' (47, Unknown)
22:39:15: Stack:    at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at SrvSurvey.game.SystemData.getDssRemainingNames()
   at SrvSurvey.PlotSysStatus.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
22:39:16: Mode change Unknown => Flying
22:39:16: Program.hideActivePlotters: 2
22:39:16: SrvSurvey.canonn.SystemPoi
22:39:16: Found system POI from Canonn for: Hypio Pri BS-H d11-9188
22:39:16: Program.hideActivePlotters: 2
22:39:36: Program.showActivePlotters: 2
22:39:49: Program.hideActivePlotters: 2
```

**Comment by njthomson** [comment]
This is a weird one, coming from .net framework code.

As you reported it did not crash the whole process, I am comfortable making no fix at this time. If this is seen again - I will investigate further and fix it.
