### ISSUE TITLE
FileNotFoundException "Could not find file 'C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0+d9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1\settings.json'." at 15/12/2023 12:52:02 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#19]
### What happened?

Deleted all folders within %appdata%\Roaming\SrvSurvey\SrvSurvey\

Run setup.exe from SrvSurvey-1.0.9.33 folder

Error as per report and screen shots

![image](https://github.com/njthomson/SrvSurvey/assets/115448925/077ef3cc-11c6-431b-84e2-b45120d8d22c)

### Version

1.0.0.0+d9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1

### Exception message

Could not find file 'C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0+d9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1\settings.json'.

### Exception stack

   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at SrvSurvey.Program.<>c__DisplayClass22_0.<moveCoreFiles>b__0(String _) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 215
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SrvSurvey.Program.moveCoreFiles(String oldFolder) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 212
   at SrvSurvey.Program.migrateToNewDataFolder() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 194
   at SrvSurvey.Main.<Main_Load>b__10_0() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 120
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

### Relevant log output

```shell
12:50:46: isMigrationValid: True, dataFolder2000: False
12:51:01: migrateToNewDataFolder: old data into common folder: C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\2.0.0.0 ...
12:51:01: Migrating old folders:
  C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0+d9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1
12:51:01: > moveCoreFiles: C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0+d9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1
12:51:01: C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0+d9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1\settings.json
12:51:01: >> moveCoreFile: C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0+d9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1\settings.json
12:51:01: Exception: Could not find file 'C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0+d9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1\settings.json'.
12:51:01: Inner exception: 
12:51:01: Stack:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at SrvSurvey.Program.<>c__DisplayClass22_0.<moveCoreFiles>b__0(String _) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 215
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SrvSurvey.Program.moveCoreFiles(String oldFolder) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 212
   at SrvSurvey.Program.migrateToNewDataFolder() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 194
   at SrvSurvey.Main.<Main_Load>b__10_0() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 120
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
12:51:05: Opening link:
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=FileNotFoundException+%22Could+not+find+file+%27C%3A%5CUsers%5CBob%5CAppData%5CRoaming%5CSrvSurvey%5CSrvSurvey%5C1.0.0.0%2Bd9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1%5Csettings.json%27.%22+at+15%2F12%2F2023+12%3A51%3A05+%2B00%3A00&what-happened=&version=1.0.0.0%2Bd9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1&exception-message=Could+not+find+file+%27C%3A%5CUsers%5CBob%5CAppData%5CRoaming%5CSrvSurvey%5CSrvSurvey%5C1.0.0.0%2Bd9c4707ce01f2f7a80ef98462712bc9eaaa2ddf1%5Csettings.json%27.&exception-stack=+++at+System.IO.FileSystem.CopyFile(String+sourceFullPath%2C+String+destFullPath%2C+Boolean+overwrite)%0D%0A+++at+SrvSurvey.Program.%3C%3Ec__DisplayClass22_0.%3CmoveCoreFiles%3Eb__0(String+_)+in+D%3A%5Ca%5CSrvSurvey%5CSrvSurvey%5CSrvSurvey%5CProgram.cs%3Aline+215%0D%0A+++at+System.Collections.Generic.List%601.ForEach(Action%601+action)%0D%0A+++at+SrvSurvey.Program.moveCoreFiles(String+oldFolder)+in+D%3A%5Ca%5CSrvSurvey%5CSrvSurvey%5CSrvSurvey%5CProgram.cs%3Aline+212%0D%0A+++at+SrvSurvey.Program.migrateToNewDataFolder()+in+D%3A%5Ca%5CSrvSurvey%5CSrvSurvey%5CSrvSurvey%5CProgram.cs%3Aline+194%0D%0A+++at+SrvSurvey.Main.%3CMain_Load%3Eb__10_0()+in+D%3A%5Ca%5CSrvSurvey%5CSrvSurvey%5CSrvSurvey%5CMain.cs%3Aline+120%0D%0A+++at+System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object+obj)%0D%0A+++at+System.Threading.ExecutionContext.RunInternal(ExecutionContext+executionContext%2C+ContextCallback+callback%2C+Object+state)%0D%0A---+End+of+stack+trace+from+previous+location+---%0D%0A+++at+System.Threading.ExecutionContext.RunInternal(ExecutionContext+executionContext%2C+ContextCallback+callback%2C+Object+state)%0D%0A+++at+System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

**Comment by njthomson** [comment]
Thank you - this will be fixed in the next build.

**Comment by njthomson** [comment]
This has now been fixed.
