### ISSUE TITLE
Error popup after carrier jump

### ISSUE THREAD

**Issue by CMDRAlexxxA** [njthomson/SrvSurvey#21]
Having been jumping the carrier since leaving Usdia, the error pops up after every carrier jump. Example below. 

**Logs:**
16:51:24: Game.event => CarrierJump
16:51:37: Game.event => Scan
16:51:37: Exception processing event 'Scan':
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unmatched system! Expected: `Usdia`, got: Nyeajaae FD-L b27-12')
   at SrvSurvey.game.SystemData.onJournalEntry(Scan entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 480
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 458
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 691
16:51:40: Game.event => Scan
16:51:40: Exception processing event 'Scan':
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unmatched system! Expected: `Usdia`, got: Nyeajaae FD-L b27-12')
   at SrvSurvey.game.SystemData.onJournalEntry(Scan entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 480
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 458
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 691
16:52:09: Opening link:

**Version:**
1.0.9.59 (Obelisks in Ruins)

**Comment by njthomson** [comment]
Thank you @CMDRAlexxxA for reporting this issue.

**Comment by njthomson** [comment]
@CMDRAlexxxA - A potential fix has been submitted, can you give build `1.0.9.71` a try?

You can download this at the bottom of [https://github.com/njthomson/SrvSurvey/actions/runs/7349969467](https://github.com/njthomson/SrvSurvey/actions/runs/7349969467)

**Comment by CMDRAlexxxA** [comment]
One jump later. No error. The app has also updated with the correct system in the Commander area.

**Comment by njthomson** [comment]
Excellent news, thank you @CMDRAlexxxA  for confirming.
