### ISSUE TITLE
Exception "Unkown site type" at 30/12/2023 14:33:21 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#23]
### What happened?

scanning at guardian site

### Version

1.0.0.0+db1601b90fe8059b16ef3e0fe25ec83d9e90e47c

### Exception message

Unkown site type

### Exception stack

   at SrvSurvey.game.GuardianSiteData.parseSettlementIdx(String name) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\GuardianSiteData.cs:line 232
   at SrvSurvey.game.GuardianSiteData.getFilename(ApproachSettlement entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\GuardianSiteData.cs:line 17
   at SrvSurvey.game.GuardianSiteData.Load(ApproachSettlement entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\GuardianSiteData.cs:line 52
   at SrvSurvey.game.Game.onJournalEntry(ApproachSettlement entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 1388
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 693

### Relevant log output

```shell
14:31:35: Program.invalidateActivePlotters: 2
14:31:38: Mode change ExternalPanel => SystemMap
14:31:38: Program.invalidateActivePlotters: 2
14:31:50: Program.hideActivePlotters: 2
14:32:20: Program.showActivePlotters: 2
14:32:38: Mode change SystemMap => ExternalPanel
14:32:38: Program.invalidateActivePlotters: 2
14:32:39: Mode change ExternalPanel => SuperCruising
14:32:39: Program.invalidateActivePlotters: 2
14:32:42: Program.hideActivePlotters: 2
```

**Comment by njthomson** [comment]
@D0bl0z - was this at a ruins or a structure? And, where there any other ground sites on that planet? Meaning: any human or Thargoid locations?

**Comment by D0bl0z** [comment]
Will have to check the site, hopefully tomorrow.CheersSent from my iPadOn 30 Dec 2023, at 19:53, njthomson ***@***.***> wrote:﻿
@D0bl0z - was this at a ruins or a structure? And, where there any other ground sites on that planet? Meaning: any human or Thargoid locations?

**Comment by njthomson** [comment]
@D0bl0z - please give [build 1.0.9.89](https://github.com/njthomson/SrvSurvey/releases/tag/1.0.9.89) a try - let me know if the problem continues.
