### ISSUE TITLE
Exception "Why no pubData for 'HIP 39768 A 14 f' / '$Ancient_Tiny_003:#index=1;'? (Newly discovered Ruins?)" at 05/01/2024 07:59:13 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#26]
### What happened?

Clicked on Ram Tah missions button and the Oops! error popped up.

### Version

1.0.0.0+3e32c88c76bdc29ad5b765867399d3340294aa97

### Exception message

Why no pubData for 'HIP 39768 A 14 f' / '$Ancient_Tiny_003:#index=1;'? (Newly discovered Ruins?)

### Exception stack

   at SrvSurvey.game.GuardianSiteData.loadPub() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\GuardianSiteData.cs:line 303
   at SrvSurvey.PlotGuardians.initialize() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\PlotGuardians.cs:line 115
   at SrvSurvey.PlotGuardians.PlotGuardians_Load(Object sender, EventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\PlotGuardians.cs:line 107
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
07:52:33: Program.invalidateActivePlotters: 4
07:53:09: Program.Creating plotter: PlotVertialStripe
07:53:09: Program.Showing plotter: PlotVertialStripe
07:54:47: Game.event => SuitLoadout
07:54:47: setSuitType: 'explorationsuit_class3' => artiemis
07:54:47: Game.event => Backpack
07:54:47: Backpack - this.onPlanet: True, firstFootfall: False
07:54:47: inferFirstFootFall: skip when at Guardian sites
07:54:50: Blink detected blinked!
07:54:50: Relic Tower 't2' heading from: 94° to: 94°
```

**Comment by njthomson** [comment]
Thank you @D0bl0z for reporting this - it should be harmless, other than triggering the Oops dialog.

Guardian structures yet don't have pubData files yet - this will be fixed in the next build.

**Comment by njthomson** [comment]
@D0bl0z - please give [build 1.0.9.89](https://github.com/njthomson/SrvSurvey/releases/tag/1.0.9.89) a try - let me know if the problem continues.
