### ISSUE TITLE
(Firewall problems) ArgumentNullException "Value cannot be null. (Parameter 'path3')" at 05/01/2024 18:23:10 +00:00

### ISSUE THREAD

**Issue by Tarl72** [njthomson/SrvSurvey#27]
### What happened?

Launched Elite, then launched SRVSurvey. SRVS says Elite in not running (I'm driving in my SRV) and there is no commander available.

### Version

1.0.0.0

### Exception message

Value cannot be null. (Parameter 'path3')

### Exception stack

   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at SrvSurvey.canonn.Canonn.loadAllStructures()
   at SrvSurvey.FormBeacons.prepareAllRows()
   at SrvSurvey.FormBeacons.FormBeacons_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Contact Details

tarlcabbot1@hotmail.com

### Relevant log output

```shell
18:19:07: SrvSurvey version: 1.0.9.0
18:19:07: Loaded settings: {
  "preferredCommander": "",
  "lastCommander": null,
  "lastFid": null,
  "targetLatLong": {
    "lat": 0.0,
    "long": 0.0
  },
  "targetLatLongActive": false,
  "autoShowBioSummary": true,
  "autoShowBioPlot": true,
  "autoShowPlotFSS": true,
  "autoShowPlotSysStatus": true,
  "skipGasGiantDSS": true,
  "skipRingsDSS": false,
  "skipLowValueDSS": true,
  "skipLowValueAmount": 1000000,
  "autoTrackCompBioScans": true,
  "skipAnalyzedCompBioScans": true,
  "autoRemoveTrackerOnSampling": true,
  "focusGameOnStart": true,
  "focusGameOnMinimize": true,
  "enableGuardianSites": true,
  "disableRuinsMeasurementGrid": false,
  "disableAerialAlignmentGrid": false,
  "hidePlottersFromCombatSuits": false,
  "hideOverlaysFromMouse": true,
  "plotterOpacity": 50.0,
  "formMainLocation": "-749, 624",
  "formLogsLocation": "0, 0, 0, 0",
  "formAllRuinsLocation": "0, 0, 0, 0",
  "formRuinsLocation": "0, 0, 0, 0",
  "formBeaconsLocation": "0, 0, 0, 0",
  "formMapEditor": "0, 0, 0, 0",
  "mapShowNotes": true,
  "blinkTigger": 134217728,
  "blinkDuration": 3000,
  "processScreenshots": true,
  "addBannerToScreenshots": true,
  "deleteScreenshotOriginal": false,
  "useGuardianAerialScreenshotsFolder": true,
  "screenshotSourceFolder": "C:\\Users\\Tarlc\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous",
  "screenshotTargetFolder": "C:\\Users\\Tarlc\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous\\converted",
  "rotateAndTruncateAlphaAerialScreenshots": true,
  "aerialAltAlpha": 1200.0,
  "aerialAltBeta": 1550.0,
  "aerialAltGamma": 1600.0,
  "idxGuardianPlotter": 0,
  "migratedAlphaSiteHeading": false,
  "GameOrange": "255, 113, 0",
  "font1": "Lucida Sans Typewriter, 16pt",
  "fontSmall": "Lucida Sans Typewriter, 8pt",
  "fontSmall2": "Century Gothic, 8pt",
  "fontSmaller": "Century Gothic, 10pt",
  "fontMiddle": "Century Gothic, 12pt",
  "fontMiddleBold": "Century Gothic, 12pt, style=Bold",
  "font2": "Century Gothic, 16pt",
  "fontBig": "Century Gothic, 22pt",
  "processIdx": 0
}
18:19:07: Watching folder: C:\Users\Tarlc\Saved Games\Frontier Developments\Elite Dangerous\
18:19:07: Watching file: C:\Users\Tarlc\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
18:19:07: Start watching screenshot folder: C:\Users\Tarlc\OneDrive\Pictures\Frontier Developments\Elite Dangerous
18:19:07: Loaded 510 ruins, 30 beacons, 153 beacons
18:19:07: SiteTemplate.Imported 6 templates
18:19:07: Main.newGame: has old game:False 
18:19:07: Game .ctor
18:19:07: Exception: Could not find file 'C:\Users\Tarlc\Saved Games\Frontier Developments\Elite Dangerous\NavRoute.json'.
18:19:07: Inner exception: 
18:19:07: Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SrvSurvey.NavRouteFile.parseFile()
   at SrvSurvey.NavRouteFile.load(Boolean watch)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
18:19:26: Exception: Value cannot be null. (Parameter 'path3')
18:19:26: Inner exception: 
18:19:26: Stack:    at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at SrvSurvey.canonn.Canonn.loadAllStructures()
   at SrvSurvey.FormBeacons.prepareAllRows()
   at SrvSurvey.FormBeacons.FormBeacons_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
18:19:34: Opening link:
https://github.com/njthomson/SrvSurvey/issues

18:23:10: Opening link:
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=ArgumentNullException+%22Value+cannot+be+null.+(Parameter+%27path3%27)%22+at+05%2F01%2F2024+18%3A23%3A10+%2B00%3A00&what-happened=&version=1.0.0.0&exception-message=Value+cannot+be+null.+(Parameter+%27path3%27)&exception-stack=+++at+System.ArgumentNullException.Throw(String+paramName)%0D%0A+++at+System.IO.Path.Combine(String+path1%2C+String+path2%2C+String+path3)%0D%0A+++at+SrvSurvey.canonn.Canonn.loadAllStructures()%0D%0A+++at+SrvSurvey.FormBeacons.prepareAllRows()%0D%0A+++at+SrvSurvey.FormBeacons.FormBeacons_Load(Object+sender%2C+EventArgs+e)%0D%0A+++at+System.Windows.Forms.Form.OnLoad(EventArgs+e)%0D%0A+++at+System.Windows.Forms.Control.CreateControl(Boolean+fIgnoreVisible)%0D%0A+++at+System.Windows.Forms.Control.CreateControl()%0D%0A+++at+System.Windows.Forms.Control.WmShowWindow(Message%26+m)%0D%0A+++at+System.Windows.Forms.Control.WndProc(Message%26+m)%0D%0A+++at+System.Windows.Forms.ScrollableControl.WndProc(Message%26+m)%0D%0A+++at+System.Windows.Forms.Form.WndProc(Message%26+m)%0D%0A+++at+System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message%26+m)%0D%0A+++at+System.Windows.Forms.NativeWindow.Callback(IntPtr+hWnd%2C+WM+msg%2C+IntPtr+wparam%2C+IntPtr+lparam)
```

**Comment by njthomson** [comment]
Thank you @Tarl72 for reporting this.

It failed due to a missing common file `NavRoute.json`, is this a fresh install of Elite Dangerous?

Either way - I will fix this for the next build.

**Comment by Tarl72** [comment]
Hi,

It's a fresh install of your add on, I've been playing Elite on my PC for a while. I heard about the SRVSurvey on the latest BurrPit podcast and can't wait to try it out. Good luck.

Tarl (CMDR Cabbot1)

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by njthomson** [comment]
@Tarl72 - please give [build 1.0.9.89](https://github.com/njthomson/SrvSurvey/releases/tag/1.0.9.89) a try - let me know if the problem continues.

**Comment by Tarl72** [comment]
Hi again,

Unfortunately, it doesn't seem to have worked. I'm still getting the '?' in the Commander section as well as the claim that Elite isn't running. Also, I know it's a false positive, but the latest setup.exe, Launcher.exe and SrvSurvey.exe are getting flagged as viruses by Norton360 (I've told it to restore them and ignore the flag in future). Here is the latest log text.

20:48:13: SrvSurvey version: 1.0.9.89
20:48:13: New log file: C:\Users\Tarlc\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240105_204813.txt
20:48:13: dataFolder: C:\Users\Tarlc\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0
20:48:13: Loaded settings: {
  "preferredCommander": "",
  "lastCommander": null,
  "lastFid": null,
  "watchedJournalFolder": "C:\\Users\\Tarlc\\Saved Games\\Frontier Developments\\Elite Dangerous\\",
  "hideJournalWriteTimer": false,
  "targetLatLong": {
    "lat": 0.0,
    "long": 0.0
  },
  "targetLatLongActive": false,
  "autoShowBioSummary": true,
  "autoShowBioPlot": true,
  "autoShowPlotFSS": true,
  "autoShowGuardianSummary": true,
  "autoShowRamTah": true,
  "autoShowPlotSysStatus": true,
  "skipGasGiantDSS": true,
  "skipRingsDSS": false,
  "skipLowValueDSS": true,
  "skipLowValueAmount": 1000000,
  "autoTrackCompBioScans": true,
  "skipAnalyzedCompBioScans": true,
  "autoRemoveTrackerOnSampling": true,
  "useExternalData": true,
  "autoLoadPriorScans": true,
  "skipPriorScansLowValue": false,
  "skipPriorScansLowValueAmount": 1000000,
  "showCanonnSignalsOnRadar": true,
  "useSmallCirclesWithCanonn": true,
  "hideMyOwnCanonnSignals": true,
  "focusGameOnStart": true,
  "focusGameOnMinimize": true,
  "enableGuardianSites": true,
  "enableEarlyGuardianStructures": false,
  "disableRuinsMeasurementGrid": false,
  "disableAerialAlignmentGrid": false,
  "hidePlottersFromCombatSuits": false,
  "hideOverlaysFromMouse": true,
  "autoShowFlightWarnings": true,
  "highGravityWarningLevel": 1.0,
  "plotterOpacity": 50.0,
  "formMainLocation": "-851, -202",
  "formLogsLocation": "0, 0, 0, 0",
  "formAllRuinsLocation": "0, 0, 0, 0",
  "formRuinsLocation": "0, 0, 0, 0",
  "formBeaconsLocation": "0, 0, 0, 0",
  "formMapEditor": "0, 0, 0, 0",
  "formRamTah": "0, 0, 0, 0",
  "mapShowNotes": true,
  "blinkTigger": 134217728,
  "blinkDuration": 3000,
  "processScreenshots": false,
  "addBannerToScreenshots": true,
  "deleteScreenshotOriginal": false,
  "useGuardianAerialScreenshotsFolder": true,
  "screenshotSourceFolder": "C:\\Users\\Tarlc\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous",
  "screenshotTargetFolder": "C:\\Users\\Tarlc\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous\\converted",
  "rotateAndTruncateAlphaAerialScreenshots": true,
  "aerialAltAlpha": 1200.0,
  "aerialAltBeta": 1550.0,
  "aerialAltGamma": 1600.0,
  "idxGuardianPlotter": 0,
  "migratedAlphaSiteHeading": false,
  "inferColor": "102, 255, 255",
  "inferTolerance": 25,
  "inferThreshold": 0.002,
  "dataFolder1100": true,
  "pubDataSettlementTemplate": 0,
  "pubDataGuardian": 0,
  "processIdx": 0
}
20:48:13: Watching folder: C:\Users\Tarlc\Saved Games\Frontier Developments\Elite Dangerous\
20:48:13: Watching file: C:\Users\Tarlc\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
20:48:13: isMigrationValid: False, dataFolder1100: True
20:48:13: updatePubData ...
20:48:13: Loaded 512 ruins, 30 beacons, 153 beacons
20:48:13: Using settlementTemplates.json app package
20:48:13: Reading settlementTemplates.json: C:\Users\Tarlc\Downloads\SrvSurvey-1.0.9.89\settlementTemplates.json
20:48:13: SiteTemplate.Imported 8 templates
20:48:13: CodexRef init ...
20:48:13: loadCodexRef: preparing from network ...
20:48:13: Error in updatePubData:
System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SrvSurvey.net.Git.updatePubData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\Git.cs:line 26
20:48:13: System.AggregateException: One or more errors occurred. (A socket operation was attempted to an unreachable network. (us-central1-canonn-api-236217.cloudfunctions.net:443))
 ---> System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (us-central1-canonn-api-236217.cloudfunctions.net:443)
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SrvSurvey.canonn.CodexRef.loadCodexRef() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 35
   at SrvSurvey.canonn.CodexRef.init() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 22
   --- End of inner exception stack trace ---
20:49:10: updatePubData - complete
20:49:19: Exception: Value cannot be null. (Parameter 'path3')
20:49:19: Inner exception:
20:49:19: Stack:    at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at SrvSurvey.canonn.Canonn.loadAllBeacons() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\Canonn.cs:line 449
   at SrvSurvey.FormBeacons.prepareAllRows() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormBeacons.cs:line 78
   at SrvSurvey.FormBeacons.FormBeacons_Load(Object sender, EventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\FormBeacons.cs:line 72
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
20:49:55: Program.CloseAllPlotters
20:49:55: Program.Creating plotter: PlotPulse
20:49:55: Program.Showing plotter: PlotPulse

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by njthomson** [comment]
Thank you @Tarl72 for these logs, they are very helpful.

It looks like a SrvSurvey is getting blocked by a firewall, and then subsequent code is failing as it did not receive the data it expected.

I will fix those failures but the blocking  firewall is the main problem. I will add an error handler to help here, but you'll need to open the firewall for SrvSurvey.

**Comment by Tarl72** [comment]
Thanks for that. I'll have a go at disabling the firewall from this end and let you know.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by Tarl72** [comment]
YES!!!!!!! Disabled firewall and the SRVSurvey instantly worked. Many thanks for the help. Oddly, one of the SRV files was allowed by Norton Firewall, while the other was blocked. The SrvSurvey.exe in the Program Files directory was automatically allowed through the firewall, but the one in the Downloads directory was blocked.

Thanks once again for all your help, it's much appreciated.

Tarl.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by njthomson** [comment]
Glad you have it working.

And that is good extra info, I'll try adding that knowledge to the error handler, thanks!
