### ISSUE TITLE
ArgumentException "The directory name 'C:\Users\Laurent\Saved Games\Frontier Developments\Elite Dangerous\' does not exist. (Parameter 'path')" at 05/01/2024 21:26:16 +01:00

### ISSUE THREAD

**Issue by lklock** [njthomson/SrvSurvey#28]
### What happened?

Crash during first app start.
The actual location of the directory containing my jounal files is:
C:\Laurent\Saved Games\Frontier Developments\Elite Dangerous
(not the default one)

### Version

1.0.0.0

### Exception message

The directory name 'C:\Users\Laurent\Saved Games\Frontier Developments\Elite Dangerous\' does not exist. (Parameter 'path')

### Exception stack

   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at SrvSurvey.Status..ctor(Boolean watch)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by njthomson** [comment]
Thank you @lklock for reporting this - this is a known issue in the Microsoft App Store build.

If you are comfortable using the unsigned build, you can install the latest from [https://github.com/njthomson/SrvSurvey/releases](https://github.com/njthomson/SrvSurvey/releases).

In the mean time, I am looking into getting that specific fix pushed into the official build.

**Comment by lklock** [comment]
I just installed the latest release and it works now.
Thank you !

**Comment by njthomson** [comment]
Thank you @lklock for letting me know.

I have submitted a fix for the Microsoft App Store, but it takes a few days for the submission to go through.

At this time I would **not** recommend returning to that now you've used the GitHub build, but it would be safe for the next major release coming up soon.
