### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 06/01/2024 19:59:13 +00:00

### ISSUE THREAD

**Issue by TonyFlury** [njthomson/SrvSurvey#34]
### What happened?

I think this error occurred when I was exiting the game, but I can't be sure.

### Version

1.0.0.0+3e32c88c76bdc29ad5b765867399d3340294aa97

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.PlotSysStatus.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Contact Details

anthony.flury@btinternet.com

### Relevant log output

```shell
19:57:33: Mode change Landed => Offline
19:57:33: Program.invalidateActivePlotters: 4
19:57:33: Main.Shutdown: Commander:Chonaire
19:57:33: Main.removeGame, has old game: True
19:57:33: Program.CloseAllPlotters
19:57:33: Program.Closing plotter: PlotPulse
19:57:33: Exception: Object reference not set to an instance of an object.
19:57:33: Inner exception: 
19:57:33: Stack:    at SrvSurvey.PlotSysStatus.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
19:58:14: Opening link:
https://github.com/njthomson/SrvSurvey/issues
```

**Comment by njthomson** [comment]
Thank you @TonyFlury for reporting this - it will be fixed in the next build.

**Comment by njthomson** [comment]
@TonyFlury - this has been fixed with build: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.6
