### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 07/01/2024 20:26:37 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#36]
### What happened?

Not sure when the Oops! happened?
I jumped to Col 173 sector oe-p d6-11, FSS then supercruised to B 3.
Landed at ancient ruins (3) and deployed the SRV
Noticed that the overlay was missing.
Was going to restart SrvSurvey and noticed the Oops! window on the taskbar.

### Version

1.0.0.0+3e32c88c76bdc29ad5b765867399d3340294aa97

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.game.SystemSettlementSummary.<>c__DisplayClass6_0.<forRuins>b__0(GuardianRuinSummary _) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\GuardianSiteData.cs:line 802
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at SrvSurvey.game.SystemSettlementSummary.forRuins(SystemData systemData, SystemBody body, Int32 idx) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\GuardianSiteData.cs:line 802
   at SrvSurvey.game.SystemData.prepSettlements() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 1007
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 265
   at SrvSurvey.Main.Game_modeChanged(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 374
   at SrvSurvey.game.Game.fireUpdate(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 213
   at SrvSurvey.game.Game.fireUpdate(Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 207
   at SrvSurvey.game.Game.setLocations(ISystemDataStarter entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 1052
   at SrvSurvey.game.Game.onJournalEntry(FSDJump entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 800
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 693

### Contact Details

qbot2@aol.com

### Relevant log output

```shell
20:23:12: Mode change Landed => RolePanel
20:23:12: Program.invalidateActivePlotters: 2
20:23:16: Mode change RolePanel => Landed
20:23:16: Program.invalidateActivePlotters: 2
20:23:19: Mode change Landed => InSrv
20:23:19: Program.invalidateActivePlotters: 2
20:24:05: Mode change InSrv => InternalPanel
20:24:05: Program.invalidateActivePlotters: 2
20:24:36: Mode change InternalPanel => InSrv
20:24:36: Program.invalidateActivePlotters: 2
```

**Comment by njthomson** [comment]
@D0bl0z - can you try this build? https://github.com/njthomson/SrvSurvey/actions/runs/7437160359

**Comment by njthomson** [comment]
@D0bl0z - give this build a try instead: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.6

**Comment by Raghav0107** [comment]
I have a similar issue with the latest build (1.1.0.6) Was on a planet and noticed the overlay disappeared, then relaunched and got this

NullReferenceException:Object reference not set to an instance of an object.

   at SrvSurvey.game.SystemData.onJournalEntry(CodexEntry entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by njthomson** [comment]
Raghav0107 - would you be able to share the SrvSurvey logs from this session?

**Comment by njthomson** [comment]
Please let me know if you see this again.
