### ISSUE TITLE
ArgumentOutOfRangeException "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')" at 15/01/2024 14:11:37 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#39]
### What happened?

Launched SrvSurvey, launched Elite, noticed the Oops window.

### Version

1.1.0.13

### Exception message

Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

### Exception stack

   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SrvSurvey.JournalFile.walk(Int32 index, Boolean searchUp, Func`2 func) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 198
   at SrvSurvey.JournalFile.walkDeep(Int32 index, Boolean searchUp, Func`2 func, Func`2 finishWhen) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 171
   at SrvSurvey.game.Game.initSystemData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 599
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 493
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 718

### Contact Details

qbot2@aol.com

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1701","build":"r298704/r0 ","timestamp":"2024-01-15T13:56:43Z","event":"Fileheader"}
13:57:48: Game.event => LoadGame
13:57:48: Game.initializeFromJournal: BEGIN  (FID:), journals.Count:3
13:57:48: Loaded data from: C:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\F4577557-live.json
13:57:48: Game.initSystemData: rewind to last FSDJump or CarrierJump
13:57:48: Reading: Journal.2024-01-15T101050.01.log
13:57:48: Game.initSystemData: last location: 'Col 173 Sector KY-Q d5-87' (2999992699219)
13:57:48: Reading: Journal.2024-01-15T072100.01.log
13:57:48: Reading: Journal.2024-01-14T090502.01.log
13:57:48: Reading: Journal.2024-01-14T084945.01.log
13:57:48: Reading: Journal.2024-01-14T082503.01.log
13:57:48: Exception processing event 'LoadGame':
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SrvSurvey.JournalFile.walk(Int32 index, Boolean searchUp, Func`2 func) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 198
   at SrvSurvey.JournalFile.walkDeep(Int32 index, Boolean searchUp, Func`2 func, Func`2 finishWhen) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 171
   at SrvSurvey.game.Game.initSystemData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 599
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 493
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 718
13:57:55: Changed hasLatLong: True, has nearBody: False, nearBody matches: False
13:57:55: setCurrentBody by name: Col 173 Sector KY-Q d5-87 AB 7 c
13:57:55: setCurrentBody: No systemData - ignoring bodyName: Col 173 Sector KY-Q d5-87 AB 7 c
13:57:55: Mode change MainMenu => Landed
13:58:05: Mode change Landed => RolePanel
13:58:08: Mode change RolePanel => Landed
13:58:14: Mode change Landed => OnFoot
13:59:31: Mode change OnFoot => Landed
14:11:05: Opening link: (length: 1499)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=ArgumentOutOfRangeException+%22Index+was+out+of+range.+Must+be+non-negative+and+less+than+the+size+of+the+collecti
```

**Comment by njthomson** [comment]
This is the same as issue #40 - which has a fix pending.
