### ISSUE TITLE
ArgumentOutOfRangeException "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')" at 16/01/2024 12:57:09 +00:00

### ISSUE THREAD

**Issue by D0bl0z** [njthomson/SrvSurvey#40]
### What happened?

Started SrvSurvey, started the game, Oops screen was there - no overlays.

### Version

1.1.0.13

### Exception message

Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

### Exception stack

   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SrvSurvey.JournalFile.walk(Int32 index, Boolean searchUp, Func`2 func) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 198
   at SrvSurvey.JournalFile.walkDeep(Int32 index, Boolean searchUp, Func`2 func, Func`2 finishWhen) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 171
   at SrvSurvey.game.Game.initSystemData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 599
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 493
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 718

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1701","build":"r298704/r0 ","timestamp":"2024-01-16T12:52:34Z","event":"Fileheader"}
12:53:38: Game.initSystemData: rewind to last FSDJump or CarrierJump
12:53:38: Reading: Journal.2024-01-15T135648.01.log
12:53:38: Game.initSystemData: last location: 'Col 173 Sector KY-Q d5-87' (2999992699219)
12:53:38: Reading: Journal.2024-01-15T101050.01.log
12:53:38: Reading: Journal.2024-01-15T072100.01.log
12:53:38: Reading: Journal.2024-01-14T090502.01.log
12:53:38: Reading: Journal.2024-01-14T084945.01.log
12:53:38: Reading: Journal.2024-01-14T082503.01.log
12:53:38: Exception processing event 'LoadGame':
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SrvSurvey.JournalFile.walk(Int32 index, Boolean searchUp, Func`2 func) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 198
   at SrvSurvey.JournalFile.walkDeep(Int32 index, Boolean searchUp, Func`2 func, Func`2 finishWhen) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 171
   at SrvSurvey.game.Game.initSystemData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 599
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 493
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 718
12:53:45: Changed hasLatLong: True, has nearBody: False, nearBody matches: False
12:53:45: setCurrentBody by name: Col 173 Sector KY-Q d5-87 AB 7 e
12:53:45: setCurrentBody: No systemData - ignoring bodyName: Col 173 Sector KY-Q d5-87 AB 7 e
12:53:45: Mode change MainMenu => Landed
12:54:03: Mode change Landed => RolePanel
12:54:05: Mode change RolePanel => Landed
12:54:11: Mode change Landed => OnFoot
12:54:54: Mode change OnFoot => Landed
12:55:07: Mode change Landed => CommsPanel
12:55:11: Mode change CommsPanel => Landed
12:55:23: Mode change Landed => Flying
```

**Comment by D0bl0z** [comment]
Closing SrvSurvey, and re opening SrvSurvey seems to fix the problem and overlays work.

**Comment by njthomson** [comment]
Thank you @D0bl0z for reporting this, and I am glad a restart solves the problem.

**Comment by njthomson** [comment]
A fix will be present in the next build.

**Comment by njthomson** [comment]
@D0bl0z  - please try this build and let me know if it keeps happening: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.20
