### ISSUE TITLE
InvalidCastException "Unable to cast object of type 'SrvSurvey.Shutdown' to type 'SrvSurvey.Fileheader'." at 1/17/2024 6:32:53 PM -05:00

### ISSUE THREAD

**Issue by rbradh53** [njthomson/SrvSurvey#41]
### What happened?

Don't know, just looked up and saw error message

### Version

1.1.0.10

### Exception message

Unable to cast object of type 'SrvSurvey.Shutdown' to type 'SrvSurvey.Fileheader'.

### Exception stack

   at SrvSurvey.JournalFile..ctor(String filepath)
   at SrvSurvey.JournalFile.walkDeep(Int32 index, Boolean searchUp, Func`2 func, Func`2 finishWhen)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1701","build":"r298704/r0 ","timestamp":"2024-01-17T23:01:57Z","event":"Fileheader"}
18:23:08: Program.Closing plotter: PlotFSS
18:23:10: Mode change SuperCruising => RolePanel
18:23:11: Mode change RolePanel => ExternalPanel
18:23:17: Mode change ExternalPanel => SuperCruising
18:25:34: Mode change SuperCruising => SAA
18:26:20: Mode change SAA => SuperCruising
18:27:05: Changed hasLatLong: True, has nearBody: False, nearBody matches: False
18:27:05: setCurrentBody by name: Byeia Euq VL-C d13-17 3
18:27:05: setCurrentBody: No systemData - ignoring bodyName: Byeia Euq VL-C d13-17 3
18:27:49: Mode change SuperCruising => GlideMode
18:27:58: Mode change GlideMode => Flying
18:28:48: Mode change Flying => Landed
18:28:49: Mode change Landed => RolePanel
18:28:50: Mode change RolePanel => Landed
18:28:55: Mode change Landed => OnFoot
18:29:36: Mode change OnFoot => Landed
18:29:52: Mode change Landed => Flying
18:31:29: Opening link: (length: 1550)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=InvalidCastException+%22Unable+to+cast+object+of+type+%27SrvSurvey.Shutdown%27+to+type+%27SrvSurvey.Fileheader%27.

18:31:29: Opening link: (length: 1550)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=InvalidCastException+%22Unable+to+cast+object+of+type+%27SrvSurvey.Shutdown%27+to+type+%27SrvSurvey.Fileheader%27.

18:32:53: Opening link: (length: 2833)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=InvalidCastException+%22Unable+to+cast+object+of+type+%27SrvSurvey.Shutdown%27+to+type+%27SrvSurvey.Fileheader%27.
```

**Comment by njthomson** [comment]
@rbradh53 thank you for reporting this.

**Comment by njthomson** [comment]
A fix will be present in the next build.

**Comment by njthomson** [comment]
@rbradh53  - please try this build and let me know if it keeps happening: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.20
