### ISSUE TITLE
ArgumentException "The directory name 'C:\Users\Ecaep\Saved Games\Frontier Developments\Elite Dangerous\' does not exist. (Parameter 'path')" at 1/19/2024 8:16:23 PM -08:00

### ISSUE THREAD

**Issue by Kelalatir** [njthomson/SrvSurvey#43]
### What happened?

Happens whenever both Elite Dangerous and SRV Survey are both running, and if the path to the elite dangerous logs does not exist.  In my case I have the logs on a different drive.  Once I corrected the path, the app works, but it took me quite a while to figure out why the app crashed on launch every time.

### Version

1.1.0.17

### Exception message

The directory name 'C:\Users\Ecaep\Saved Games\Frontier Developments\Elite Dangerous\' does not exist. (Parameter 'path')

### Exception stack

   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at SrvSurvey.Status..ctor(Boolean watch)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

### Contact Details

cardinalcs@gmail.com

### Relevant log output

```shell
20:10:40: loadCodexRef: reading codex/ref from disk
20:10:40: prepBioRef: reading bioRef from disk
20:10:40: loadOrganicRewards: reading organic rewards from disk
20:10:40: CodexRef init - complete
20:10:40: Main.newGame: has old game:False 
20:10:40: Game .ctor
20:10:40: Exception: The directory name 'C:\Users\Ecaep\Saved Games\Frontier Developments\Elite Dangerous\' does not exist. (Parameter 'path')
20:10:40: Inner exception: 
20:10:40: Stack:    at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at SrvSurvey.Status..ctor(Boolean watch)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
20:11:20: Opening link: (length: 7156)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=ArgumentException+%22The+directory+name+%27C%3A%5CUsers%5CEcaep%5CSaved+Games%5CFrontier+Developments%5CElite+Dang

20:12:04: pubDataSettlementTemplate - local: 0, remote: 16
20:12:04: Downloading settlementTemplates.json
20:12:04: pubDataGuardian - local: 0, remote: 16
20:12:04: Downloading allRuins.json
20:12:04: Downloading allStructuresRuins.json
20:12:04: Downloading guardian.zip ...
20:12:05: https://raw.githubusercontent.com/njthomson/SrvSurvey/main/data/guardian.zip => C:\Users\Ecaep\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\guardian.zip
20:12:06: Loaded 512 ruins, 30 beacons, 155 beacons
20:12:06: Downloading guardian.zip - complete
20:12:06: updatePubData - complete
```

**Comment by njthomson** [comment]
Thank you @Kelalatir for reporting this.

**Comment by njthomson** [comment]
@Kelalatir  - please try this build and let me know if it keeps happening: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.20
