### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 21.01.2024 22:48:11 +01:00

### ISSUE THREAD

**Issue by toso101** [njthomson/SrvSurvey#44]
### What happened?

Oops while playing ed

### Version

1.0.0.0+3e32c88c76bdc29ad5b765867399d3340294aa97

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.PlotSysStatus.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Contact Details

tsommer@ringofen.de

**Comment by njthomson** [comment]
Thank you @toso101 for reporting this - it should be fixed in the next build.

**Comment by njthomson** [comment]
@toso101 - please try this build and let me know if it keeps happening: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.20
