### ISSUE TITLE
FileNotFoundException "Could not find file 'C:\Users\ash\Saved Games\Frontier Developments\Elite Dangerous\NavRoute.json'." at 23/01/2024 23:43:36 +00:00

### ISSUE THREAD

**Issue by Minecrafter8001** [njthomson/SrvSurvey#47]
### What happened?

first launch after installing from MS store

### Version

1.0.0.0

### Exception message

Could not find file 'C:\Users\username\Saved Games\Frontier Developments\Elite Dangerous\NavRoute.json'.

### Exception stack

   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SrvSurvey.NavRouteFile.parseFile()
   at SrvSurvey.NavRouteFile.load(Boolean watch)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
23:42:32: Watching folder: C:\Users\username\Saved Games\Frontier Developments\Elite Dangerous\
23:42:32: Watching file: C:\Users\username\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
23:42:32: Loaded 510 ruins, 30 beacons, 153 beacons
23:42:32: SiteTemplate.Imported 6 templates
23:42:32: Main.newGame: has old game:False 
23:42:32: Game .ctor
23:42:32: Exception: Could not find file 'C:\Users\username\Saved Games\Frontier Developments\Elite Dangerous\NavRoute.json'.
23:42:32: Inner exception: 
23:42:32: Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SrvSurvey.NavRouteFile.parseFile()
   at SrvSurvey.NavRouteFile.load(Boolean watch)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
23:43:09: Opening link:
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crusername-report.yml&title=FileNotFoundException+%22Could+not+find+file+%27C%3A%5CUsers%5Cusername%5CSaved+Games%5CFrontier+Developments%5CElite+Dangerous%5CNavRoute.json%27.%22+at+23%2F01%2F2024+23%3A43%3A09+%2B00%3A00&what-happened=first+launch+after+installing+from+MS+store&version=1.0.0.0&exception-message=Could+not+find+file+%27C%3A%5CUsers%5Cusername%5CSaved+Games%5CFrontier+Developments%5CElite+Dangerous%5CNavRoute.json%27.&exception-stack=+++at+Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String+fullPath%2C+FileMode+mode%2C+FileAccess+access%2C+FileShare+share%2C+FileOptions+options)%0D%0A+++at+Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String+fullPath%2C+FileMode+mode%2C+FileAccess+access%2C+FileShare+share%2C+FileOptions+options%2C+Int64+preallocationSize%2C+Nullable%601+unixCreateMode)%0D%0A+++at+System.IO.Strategies.OSFileStreamStrategy..ctor(String+path%2C+FileMode+mode%2C+FileAccess+access%2C+FileShare+share%2C+FileOptions+options%2C+Int64+preallocationSize%2C+Nullable%601+unixCreateMode)%0D%0A+++at+System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String+path%2C+FileMode+mode%2C+FileAccess+access%2C+FileShare+share%2C+FileOptions+options%2C+Int64+preallocationSize%2C+Nullable%601+unixCreateMode)%0D%0A+++at+System.IO.FileStream..ctor(String+path%2C+FileMode+mode%2C+FileAccess+access%2C+FileShare+share)%0D%0A+++at+SrvSurvey.NavRouteFile.parseFile()%0D%0A+++at+SrvSurvey.NavRouteFile.load(Boolean+watch)%0D%0A+++at+SrvSurvey.game.Game..ctor(String+cmdr)%0D%0A+++at+SrvSurvey.Main.newGame()%0D%0A+++at+SrvSurvey.Main.Main_Load(Object+sender%2C+EventArgs+e)%0D%0A+++at+System.Windows.Forms.Form.OnLoad(EventArgs+e)%0D%0A+++at+System.Windows.Forms.Control.CreateControl(Boolean+fIgnoreVisible)%0D%0A+++at+System.Windows.Forms.Control.CreateControl()%0D%0A+++at+System.Windows.Forms.Control.WmShowWindow(Message%26+m)%0D%0A+++at+System.Windows.Forms.Control.WndProc(Message%26+m)%0D%0A+++at+System.Windows.Forms.NativeWindow.Callback(IntPtr+hWnd%2C+WM+msg%2C+IntPtr+wparam%2C+IntPtr+lparam)```

**Comment by njthomson** [comment]
Hi @Minecrafter8001 - There is a better fix in progress already, but in the mean time you can set the correct folder for your journal files with this setting:
![image](https://github.com/njthomson/SrvSurvey/assets/3903773/c45d0178-4184-4eb2-bfcc-f907d4f726bb)

**Comment by njthomson** [comment]
Recent builds have a fix for this now.
