### ISSUE TITLE
ArgumentNullException "Value cannot be null. (Parameter 'text')" at 27/01/2024 08:30:28 +00:00

### ISSUE THREAD

**Issue by brammmers** [njthomson/SrvSurvey#49]
### What happened?

Was looking at the guardian sites list, right-clicked on "GR 1" row, oops dialog appeared

### Version

1.1.0.25

### Exception message

Value cannot be null. (Parameter 'text')

### Exception stack

   at System.Windows.Forms.ArgumentValidation.ThrowIfNullOrEmpty(String argument, String paramName)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at SrvSurvey.FormBeacons.notesToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1701","build":"r299332/r0 ","timestamp":"2024-01-27T07:36:31Z","event":"Fileheader"}
08:26:31: Game.event => Music
08:26:31: Mode change SuperCruising => GlideMode
08:26:31: Program.Closing plotter: PlotSysStatus
08:26:39: Game.event => Music
08:26:44: Mode change GlideMode => ExternalPanel
08:26:44: Program.Creating plotter: PlotSysStatus
08:26:44: Searching journals for last touchdown location... (mode: ExternalPanel)
08:26:44: searchJournalsDeep: count: 1
08:26:44: Program.Showing plotter: PlotSysStatus
08:26:48: Mode change ExternalPanel => Flying
08:26:48: Program.Closing plotter: PlotSysStatus
08:26:52: Game.event => Music
08:27:29: Game.event => Music
08:27:30: Mode change Flying => Docked
08:27:34: Mode change Docked => StationServices
08:29:46: loadAllRuins: incRamTahLogs: False
08:29:46: Rendering 30 beacons, 155 structures
08:30:18: Exception: Value cannot be null. (Parameter 'text')
08:30:18: Inner exception: 
08:30:18: Stack:    at System.Windows.Forms.ArgumentValidation.ThrowIfNullOrEmpty(String argument, String paramName)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at SrvSurvey.FormBeacons.notesToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by brammmers** [comment]
Chose "notes" from pop up context menu

**Comment by njthomson** [comment]
Doh, this will be an easy fix.

**Comment by njthomson** [comment]
Fix is pending for the next build.

**Comment by njthomson** [comment]
This is fixed in most recent builds - let me know if it happens again.
