### ISSUE TITLE
ArgumentNullException "Value cannot be null. (Parameter 'source')" at 2/3/2024 9:47:43 AM -05:00

### ISSUE THREAD

**Issue by PhoenixBlue0** [njthomson/SrvSurvey#50]
### What happened?

The SRV overlay disappeared at some point while I was playing. I restarted the SRV Survey program, and it threw up this message. It can no longer detect the game state.

### Version

1.1.0.7

### Exception message

Value cannot be null. (Parameter 'source')

### Exception stack

   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Sum[TSource,TResult,TAccumulator](IEnumerable`1 source, Func`2 selector)
   at SrvSurvey.game.Game.onJournalEntry(Cargo entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.initCargoData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1701","build":"r299332/r0 ","timestamp":"2024-02-03T11:12:31Z","event":"Fileheader"}
09:46:09: Game.initSystemData: playForwards 'Scan' (2/3/2024 2:42:43 PM)
09:46:09: Game.initSystemData: playForwards 'Scan' (2/3/2024 2:42:45 PM)
09:46:09: Game.initSystemData: playForwards 'Scan' (2/3/2024 2:42:47 PM)
09:46:09: Game.initSystemData: playForwards 'Scan' (2/3/2024 2:42:49 PM)
09:46:09: Game.initSystemData: playForwards 'Scan' (2/3/2024 2:42:51 PM)
09:46:09: Game.initSystemData: playForwards 'Scan' (2/3/2024 2:42:54 PM)
09:46:09: Game.initSystemData: playForwards 'FSSAllBodiesFound' (2/3/2024 2:42:54 PM)
09:46:09: Game.initSystemData: playForwards 'SAAScanComplete' (2/3/2024 2:44:45 PM)
09:46:09: Game.initSystemData: playForwards 'Scan' (2/3/2024 2:44:46 PM)
09:46:09: Game.initSystemData: playForwards 'SAAScanComplete' (2/3/2024 2:45:40 PM)
09:46:09: Game.initSystemData: playForwards 'Scan' (2/3/2024 2:45:40 PM)
09:46:09: Game.initSystemData: complete 'Blaea Eun FA-A d16' (554143058691), bodyCount: 18
09:46:09: Game.initCargoData: rewind to last Cargo
09:46:09: Game.initCargoData: Processing 1 cargo journal items forwards...
09:46:09: Game.initCargoData: cargo playForwards 'Cargo' (2/3/2024 11:27:30 AM)
09:46:09: Exception: Value cannot be null. (Parameter 'source')
09:46:09: Inner exception: 
09:46:09: Stack:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Sum[TSource,TResult,TAccumulator](IEnumerable`1 source, Func`2 selector)
   at SrvSurvey.game.Game.onJournalEntry(Cargo entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.initCargoData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
09:46:12: Opening link: (length: 45)
https://github.com/njthomson/SrvSurvey/issues

09:46:49: Opening link: (length: 4598)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=ArgumentNullException+%22Value+cannot+be+null.+(Parameter+%27source%27)%22+at+2%2F3%2F2024+9%3A46%3A49+AM+-05%3A00
```

**Comment by PhoenixBlue0** [comment]
This seems to have been fixed with an update to 1.1.0.37.
