### ISSUE TITLE
Exception "Why no journals here?" at 3-2-2024 17:47:48 +01:00

### ISSUE THREAD

**Issue by S-K-Tiger** [njthomson/SrvSurvey#51]
### What happened?

I tried clearing leftover tracked locations after having closed the game.

### Version

1.0.0.0

### Exception message

Why no journals here?

### Exception stack

   at SrvSurvey.game.Data.Save()
   at SrvSurvey.PlotTrackers.processCommand(String msg, LatLong2 location)
   at SrvSurvey.FormSettings.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
17:46:33: Mode change MainMenu => Offline
17:46:33: Main.Shutdown: Commander:Vicar Tineamica
17:46:33: Main.removeGame, has old game: True
17:46:33: Program.CloseAllPlotters
17:46:33: Program.Closing plotter: PlotSysStatus
17:46:33: Program.Closing plotter: PlotPulse
17:46:45: Program.hideActivePlotters: 0
17:46:55: Exception: Why no journals here?
17:46:55: Inner exception: 
17:46:55: Stack:    at SrvSurvey.game.Data.Save()
   at SrvSurvey.PlotTrackers.processCommand(String msg, LatLong2 location)
   at SrvSurvey.FormSettings.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by njthomson** [comment]
Interesting find, thanks @S-K-Tiger

**Comment by njthomson** [comment]
This will be fixed in the next build.

**Comment by njthomson** [comment]
@S-K-Tiger - please try this build and let me know if the problem continues:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.43
