### ISSUE TITLE
Exception "Unexpected variantName: '$Codex_Ent_Ground_Struct_Name;'" at 2/4/2024 12:27:38 AM -05:00

### ISSUE THREAD

**Issue by PhoenixBlue0** [njthomson/SrvSurvey#52]
### What happened?

SRV Survey threw this error message when I collected a sample from a Crystalline Shard on Winds KQ-G c10-0 c 3 a.

### Version

1.1.0.37

### Exception message

Unexpected variantName: '$Codex_Ent_Ground_Struct_Name;'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromVariant(String variantName) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 254
   at SrvSurvey.game.SystemData.onJournalEntry(ScanOrganic entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 649
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 458
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 697

**Comment by njthomson** [comment]
Thanks @PhoenixBlue0

**Comment by njthomson** [comment]
@PhoenixBlue0 - I have a fix ready. There aren't any Crystalline Shard's near my current location to confirm the fix, but I hope this will do the trick.

**Comment by njthomson** [comment]
@PhoenixBlue0 - please try this build and let me know if the problem continues:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.43

**Comment by PhoenixBlue0** [comment]
I'll fly out to one and let you know. Thanks!

- PB
