### ISSUE TITLE
ArgumentNullException "Value cannot be null. (Parameter 'path2')" at 4-2-2024 11:55:15 +01:00

### ISSUE THREAD

**Issue by S-K-Tiger** [njthomson/SrvSurvey#54]
### What happened?

Crashed on installation.
Tried installing the new version to see if I could reproduce the bug I reported earlier in the latest non-store version.

### Version

1.1.0.39

### Exception message

Value cannot be null. (Parameter 'path2')

### Exception stack

   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at SrvSurvey.game.GuardianSiteData.loadAllSites(Boolean onlyRuins)
   at SrvSurvey.net.Git.updateRawPoiAfterRefresh()
   at SrvSurvey.net.Git.refreshPublishedData()

### Relevant log output

```shell
11:54:11: Watching file: C:\Users\larsw\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
11:54:11: setFocusED: got Zero!
11:54:11: isMigrationValid: False, dataFolder1100: False
11:54:11: Using settlementTemplates.json app package
11:54:11: Reading settlementTemplates.json: C:\Users\larsw\AppData\Local\Apps\2.0\42ORKNJH.VEB\CLP8KKV7.M7Q\srvs..tion_0000000000000000_0001.0001_9e2ce3c2dfc0dd6e\settlementTemplates.json
11:54:11: SiteTemplate.Imported 13 templates
11:54:11: updatePubData ...
11:54:12: pubDataSettlementTemplate - local: 0, remote: 22
11:54:12: Updating CodexRef ...
11:54:12: CodexRef init (reset: True) ...
11:54:12: loadCodexRef: preparing from network ...
11:54:15: loadCodexRef: complete
11:54:15: prepBioRef: preparing from network ...
11:54:15: prepBioRef: complete
11:54:15: loadOrganicRewards: preparing ...
11:54:15: loadOrganicRewards: complete
11:54:15: CodexRef init - complete
11:54:15: Downloading settlementTemplates.json
11:54:16: Error in updatePubData:
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at SrvSurvey.game.GuardianSiteData.loadAllSites(Boolean onlyRuins)
   at SrvSurvey.net.Git.updateRawPoiAfterRefresh()
   at SrvSurvey.net.Git.refreshPublishedData()
11:54:16: isFirewallProblem?
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at SrvSurvey.game.GuardianSiteData.loadAllSites(Boolean onlyRuins)
   at SrvSurvey.net.Git.updateRawPoiAfterRefresh()
   at SrvSurvey.net.Git.refreshPublishedData()
```

**Comment by njthomson** [comment]
@S-K-Tiger - this should be fixed with the latest build. Please let me know if it gives you any more grief.
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.40
