### ISSUE TITLE
ArgumentNullException "Value cannot be null. (Parameter 'path2')" at 2024-02-05 11:00:37 +02:00

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#57]
### What happened?

Tried launching the app from the Start Menu after installation.  It immediately gives this error.  Game is not running yet.

Had the Windows Store version installed previously but uninstalled before installing this version.  Don't know if that's relevant.

Also saw something about the firewall in the log and tried diabling it completely, but still same error.

### Version

1.1.0.39

### Exception message

Value cannot be null. (Parameter 'path2')

### Exception stack

   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at SrvSurvey.game.GuardianSiteData.loadAllSites(Boolean onlyRuins)
   at SrvSurvey.net.Git.updateRawPoiAfterRefresh()
   at SrvSurvey.net.Git.refreshPublishedData()

### Relevant log output

```shell
10:59:52: SrvSurvey version: 1.1.0.39
10:59:52: New log file: C:\Users\*****\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240205_105952.txt
10:59:52: dataFolder: C:\Users\*****\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0
10:59:52: Loaded settings: {
  "preferredCommander": null,
  "lastCommander": null,
  "lastFid": null,
  "watchedJournalFolder": "C:\\Users\\*****\\Saved Games\\Frontier Developments\\Elite Dangerous\\",
  "hideJournalWriteTimer": false,
  "targetLatLong": {
    "lat": 0.0,
    "long": 0.0
  },
  "targetLatLongActive": false,
  "autoShowBioSummary": true,
  "autoShowBioPlot": true,
  "autoShowPlotFSS": true,
  "autoShowGuardianSummary": true,
  "autoShowRamTah": true,
  "autoShowPlotSysStatus": true,
  "skipGasGiantDSS": true,
  "skipRingsDSS": false,
  "skipLowValueDSS": true,
  "skipLowValueAmount": 1000000,
  "autoTrackCompBioScans": true,
  "skipAnalyzedCompBioScans": true,
  "autoRemoveTrackerOnSampling": true,
  "useExternalData": true,
  "autoLoadPriorScans": true,
  "skipPriorScansLowValue": false,
  "skipPriorScansLowValueAmount": 1000000,
  "showCanonnSignalsOnRadar": true,
  "useSmallCirclesWithCanonn": true,
  "hideMyOwnCanonnSignals": true,
  "focusGameOnStart": true,
  "focusGameOnMinimize": true,
  "enableGuardianSites": true,
  "enableEarlyGuardianStructures": false,
  "disableRuinsMeasurementGrid": false,
  "disableAerialAlignmentGrid": false,
  "hidePlottersFromCombatSuits": false,
  "hideOverlaysFromMouse": true,
  "autoShowFlightWarnings": true,
  "highGravityWarningLevel": 1.0,
  "plotterOpacity": 50.0,
  "formMainLocation": "568, 219",
  "formLogsLocation": "0, 0, 0, 0",
  "formAllRuinsLocation": "0, 0, 0, 0",
  "formRuinsLocation": "0, 0, 0, 0",
  "formBeaconsLocation": "0, 0, 0, 0",
  "formMapEditor": "0, 0, 0, 0",
  "formRamTah": "0, 0, 0, 0",
  "mapShowNotes": true,
  "blinkTigger": 134217728,
  "blinkDuration": 3000,
  "processScreenshots": false,
  "addBannerToScreenshots": true,
  "deleteScreenshotOriginal": false,
  "useGuardianAerialScreenshotsFolder": true,
  "screenshotSourceFolder": "C:\\Users\\*****\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous",
  "screenshotTargetFolder": "C:\\Users\\*****\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous\\converted",
  "rotateAndTruncateAlphaAerialScreenshots": true,
  "screenshotBannerColor": "Yellow",
  "screenshotBannerLocalTime": false,
  "aerialAltAlpha": 1200.0,
  "aerialAltBeta": 1550.0,
  "aerialAltGamma": 1600.0,
  "idxGuardianPlotter": 0,
  "migratedAlphaSiteHeading": false,
  "inferColor": "102, 255, 255",
  "inferTolerance": 25,
  "inferThreshold": 0.002,
  "dataFolder1100": true,
  "pubCodexRef": 1,
  "pubDataSettlementTemplate": 0,
  "pubDataGuardian": 0,
  "processIdx": 0
}
10:59:52: Reading PlotterPositions from: C:\Users\*****\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\plotters.json
10:59:52: Program.repositionPlotters: 0, rect{X=0,Y=0,Width=0,Height=0}
10:59:52: Watching folder: C:\Users\*****\Saved Games\Frontier Developments\Elite Dangerous\
10:59:52: Watching file: C:\Users\*****\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
10:59:52: setFocusED: got Zero!
10:59:52: isMigrationValid: False, dataFolder1100: True
10:59:52: Using settlementTemplates.json from pubData
10:59:52: Reading settlementTemplates.json: C:\Users\*****\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
10:59:52: SiteTemplate.Imported 13 templates
10:59:52: updatePubData ...
10:59:53: pubDataSettlementTemplate - local: 0, remote: 22
10:59:53: Downloading settlementTemplates.json
10:59:53: Error in updatePubData:
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at SrvSurvey.game.GuardianSiteData.loadAllSites(Boolean onlyRuins)
   at SrvSurvey.net.Git.updateRawPoiAfterRefresh()
   at SrvSurvey.net.Git.refreshPublishedData()
10:59:53: isFirewallProblem?
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at SrvSurvey.game.GuardianSiteData.loadAllSites(Boolean onlyRuins)
   at SrvSurvey.net.Git.updateRawPoiAfterRefresh()
   at SrvSurvey.net.Git.refreshPublishedData()
```

**Comment by S-K-Tiger** [comment]
This seems to be the same bug I encountered and reported.
See #54

**Comment by njthomson** [comment]
Thank you @Vic502 and @S-K-Tiger - these logs are helpful and I should have a fix available soon.

**Comment by Vic502** [comment]
> This seems to be the same bug I encountered and reported. See #54

Yeah, saw yours after I submitted mine.  Should maybe have checked 1st. Oh well.

**Comment by njthomson** [comment]
This should be fixed with the latest build. Please let me know if it gives you any more grief.
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.40

**Comment by Vic502** [comment]
@njthomson That fixed it, thanks!
