### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 12/02/2024 21:20:47 +00:00

### ISSUE THREAD

**Issue by Llorkess** [njthomson/SrvSurvey#62]
### What happened?

Just srvsurvey crashed

### Version

1.0.0.0

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.PlotSysStatus.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by njthomson** [comment]
Thanks for reporting this @Llorkess - you can try a recent unsigned build from https://github.com/njthomson/SrvSurvey/releases, or wait till I have recent fixes pushed to the Microsoft App store.

**Comment by njthomson** [comment]
@Llorkess - this fix has been published in the MS app store:
https://www.microsoft.com/store/productId/9NGT6RRH6B7N
