### ISSUE TITLE
ArgumentException "Requested value 'PlanetaryRing' was not found." at 17/02/2024 07:41:55 +00:00

### ISSUE THREAD

**Issue by pdavg100** [njthomson/SrvSurvey#63]
### What happened?

program would not run

### Version

1.1.0.36

### Exception message

Requested value 'PlanetaryRing' was not found.

### Exception stack

   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()

**Comment by njthomson** [comment]
Thank you @pdavg100 for reporting this. It was recently fixed, can you try again with this build?

https://github.com/njthomson/SrvSurvey/releases

It will also only occur in specific systems.

**Comment by njthomson** [comment]
@pdavg100 - let me know if you see this again in a more recent build.
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.50
