### ISSUE TITLE
ArgumentException "Requested value 'PlanetaryRing' was not found." at 02/20/24 14:32:15 -05:00

### ISSUE THREAD

**Issue by jyeary** [njthomson/SrvSurvey#65]
### What happened?

Scanning bark mounds

### Version

1.1.0.17

### Exception message

Requested value 'PlanetaryRing' was not found.

### Exception stack

   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

### Relevant log output

```shell
14:20:45: updatePubData ...
14:20:45: isMigrationValid: False, dataFolder1100: True
14:20:46: Loaded 512 ruins, 30 beacons, 155 beacons
14:20:46: Using settlementTemplates.json from pubData
14:20:46: Reading settlementTemplates.json: C:\Users\johny\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
14:20:46: SiteTemplate.Imported 13 templates
14:20:46: CodexRef init ...
14:20:46: loadCodexRef: reading codex/ref from disk
14:20:46: prepBioRef: reading bioRef from disk
14:20:46: loadOrganicRewards: reading organic rewards from disk
14:20:46: CodexRef init - complete
14:20:46: Main.newGame: has old game:False 
14:20:46: Game .ctor
14:20:46: Reading: Journal.2024-02-20T133124.01.log
14:20:46: Exception: Requested value 'PlanetaryRing' was not found.
14:20:46: Inner exception: 
14:20:46: Stack:    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
14:20:46: pubDataSettlementTemplate - local: 23, remote: 23
14:20:46: pubDataGuardian - local: 23, remote: 23
14:20:46: updatePubData - complete
```

**Comment by njthomson** [comment]
@jyeary - this has been fixed in recent builds. Can you try the latest from here and let me know if it keeps happening?

https://github.com/njthomson/SrvSurvey/releases
