### ISSUE TITLE
ArgumentException "Requested value 'PlanetaryRing' was not found." at 02/20/24 17:04:25 -05:00

### ISSUE THREAD

**Issue by jyeary** [njthomson/SrvSurvey#66]
### What happened?

Trying to start SRV Survey

### Version

1.1.0.17

### Exception message

Requested value 'PlanetaryRing' was not found.

### Exception stack

   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

### Relevant log output

```shell
17:03:33: isMigrationValid: False, dataFolder1100: True
17:03:33: Loaded 512 ruins, 30 beacons, 155 beacons
17:03:33: Using settlementTemplates.json from pubData
17:03:33: Reading settlementTemplates.json: C:\Users\johny\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
17:03:33: SiteTemplate.Imported 13 templates
17:03:33: CodexRef init ...
17:03:33: loadCodexRef: reading codex/ref from disk
17:03:33: prepBioRef: reading bioRef from disk
17:03:33: loadOrganicRewards: reading organic rewards from disk
17:03:33: CodexRef init - complete
17:03:33: Main.newGame: has old game:False 
17:03:33: Game .ctor
17:03:33: Blink detected blinked!
17:03:33: Reading: Journal.2024-02-20T133124.01.log
17:03:33: pubDataSettlementTemplate - local: 23, remote: 23
17:03:33: pubDataGuardian - local: 23, remote: 23
17:03:33: updatePubData - complete
17:03:33: Exception: Requested value 'PlanetaryRing' was not found.
17:03:33: Inner exception: 
17:03:33: Stack:    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
```

**Comment by njthomson** [comment]
This has been fixed in recent builds, can you try the latest from here:

https://github.com/njthomson/SrvSurvey/releases

Let me know if it keeps happening.
