### ISSUE TITLE
ArgumentException "The directory name 'C:\Users\graha\Saved Games\Frontier Developments\Elite Dangerous\' does not exist. (Parameter 'path')" at 21/02/2024 19:38:43 +00:00

### ISSUE THREAD

**Issue by fatlazycat** [njthomson/SrvSurvey#68]
### What happened?

I have my logs in a non standard location.

### Version

1.0.0.0

### Exception message

The directory name 'C:\Users\graha\Saved Games\Frontier Developments\Elite Dangerous\' does not exist. (Parameter 'path')

### Exception stack

   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at SrvSurvey.Status..ctor(Boolean watch)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by njthomson** [comment]
Hi @fatlazycat - there is a setting you can use to change the folder for journal items. Give that a try and let me know if it gives you grief still.

**Comment by fatlazycat** [comment]
Yeah I changed it. Was pretty obvious.

I just logged it as assumed you wouldn't want it to crash on startup :) 

Thanks for the app - looks very helpful !

**Comment by njthomson** [comment]
Thanks @fatlazycat!
