### ISSUE TITLE
Exception : Why no systemdata

### ISSUE THREAD

**Issue by Greyab** [njthomson/SrvSurvey#70]
### What happened?

Launched ED, then launched SRV Survey

### Version

1.1.0.37

### Exception message

Exception:Why no systemData?

### Exception stack

   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__10_7()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()

**Comment by Greyab** [comment]
Checked the journal entry location was correct, as I thought I may not have set that correctly.

**Comment by njthomson** [comment]
Thank you @Greyab for reporting this. I think it is an issue about timing. You might have more luck with more recent builds, and/or starting SrvSurvey before the game.

It should not matter which one is started first, but that could be a temporary fix for now.

**Comment by njthomson** [comment]
I have a local repro, a fix will be in the next build.

**Comment by njthomson** [comment]
This is fixed in the next build.

**Comment by njthomson** [comment]
Fixed as of build `1.1.0.50`
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.50
