### ISSUE TITLE
error on opening

### ISSUE THREAD

**Issue by Nicon4454** [njthomson/SrvSurvey#71]
### What happened?

running it this came up and it told me to report it to here

### Version

1.1.0.44

### Exception message

`HttpRequestException:A socket operation was attempted to an unreachable network. (raw.githubusercontent.com:443)

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SrvSurvey.net.Git.refreshPublishedData()`

### Exception stack

`HttpRequestException:A socket operation was attempted to an unreachable network. (raw.githubusercontent.com:443)

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SrvSurvey.net.Git.refreshPublishedData()`

### Relevant log output

```shell
sorry no log
```

**Comment by Nicon4454** [comment]
also the box needs a bit of work the link is hidden.
<img width="307" alt="Screenshot 2024-02-26 174134" src="https://github.com/njthomson/SrvSurvey/assets/3824774/3cc15988-d096-4719-bc3b-25ba97924a05">

**Comment by Nicon4454** [comment]
this ended up being my norton firewall

**Comment by njthomson** [comment]
Thank you @Nicon4454 for reporting these issues, and glad you solved it already.

I will use this bug to fix the sizing/clipping on the error window.

**Comment by njthomson** [comment]
This is fixed in the next build.

**Comment by njthomson** [comment]
Fixed as of build `1.1.0.50`
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.50
