### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 01/03/2024 14:39:19 +00:00

### ISSUE THREAD

**Issue by Minecrafter8001** [njthomson/SrvSurvey#72]
### What happened?

relauching after my game crashed

### Version

1.1.0.44

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.PlotPriorScans.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
14:37:48: Game.event => Embark
14:37:48: Embark - entry.onPlanet: True
14:37:48: prepSettlements: for: 'Epsilon Monocerotis' (181699347628), sites.Count: 0
14:37:48: Main.Disembark Epsilon Monocerotis A 5 a
14:37:48: Embark Lat:+30.759825, Long:+65.383911
14:37:49: Game.event => Music
14:37:49: Game.event => Music
14:37:52: Mode change OnFoot => InSrv
14:37:54: CargoFile updated: 0 items in: SRV
  
14:37:54: Game.event => Cargo
14:38:01: Main.Minimized, focusing on game...
14:38:07: Game.event => Shutdown
14:38:07: Mode change InSrv => Offline
14:38:07: Main.Shutdown: Commander:minecrafter
14:38:07: Main.removeGame, has old game: True
14:38:07: Program.CloseAllPlotters
14:38:07: Program.Closing plotter: PlotPulse
14:38:07: Exception: Object reference not set to an instance of an object.
14:38:07: Inner exception: 
14:38:07: Stack:    at SrvSurvey.PlotPriorScans.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by njthomson** [comment]
Thanks @Minecrafter8001 - this will be fixed in the next build.

**Comment by njthomson** [comment]
Fixed already, https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.55
