### ISSUE TITLE
Exception "Unexpected entryId: '2100604'" at 11/03/2024 01:17:59 +00:00

### ISSUE THREAD

**Issue by svensven** [njthomson/SrvSurvey#78]
### What happened?

Scanning a lifeform at an NSP

### Version

1.1.0.17

### Exception message

Unexpected entryId: '2100604'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromEntryId(String entryId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 227
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\net\CodexRef.cs:line 209
   at SrvSurvey.game.SystemData.onJournalEntry(CodexEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 617
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\SystemData.cs:line 458
   at SrvSurvey.game.Game.initSystemData() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 641
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 494
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 733

### Relevant log output

```shell
{ "timestamp":"2024-03-11T01:11:36Z", "event":"CodexEntry", "EntryID":2100604, "Name":"$Codex_Ent_L_Cry_IcCry_Pur_Name;", "Name_Localised":"Purpureum Ice Crystals", "SubCategory":"$Codex_SubCategory_Organic_Structures;", "SubCategory_Localised":"Organic structures", "Category":"$Codex_Category_Biology;", "Category_Localised":"Biological and Geological", "Region":"$Codex_RegionName_39;", "Region_Localised":"Tenebrae", "System":"Swauwry UY-S d3-5", "SystemAddress":190127804067, "BodyID":18, "NearestDestination":"$Fixed_Event_Life_Ring;", "NearestDestination_Localised":"Notable stellar phenomena", "Traits":[ "o_l_freze" ], "IsNewEntry":true, "VoucherAmount":50000 }
{ "timestamp":"2024-03-11T01:13:31Z", "event":"CodexEntry", "EntryID":2100604, "Name":"$Codex_Ent_L_Cry_IcCry_Pur_Name;", "Name_Localised":"Purpureum Ice Crystals", "SubCategory":"$Codex_SubCategory_Organic_Structures;", "SubCategory_Localised":"Organic structures", "Category":"$Codex_Category_Biology;", "Category_Localised":"Biological and Geological", "Region":"$Codex_RegionName_39;", "Region_Localised":"Tenebrae", "System":"Swauwry UY-S d3-5", "SystemAddress":190127804067, "BodyID":18, "NearestDestination":"$Fixed_Event_Life_Ring;", "NearestDestination_Localised":"Notable stellar phenomena", "Traits":[ "o_l_freze" ] }
{ "timestamp":"2024-03-11T01:15:01Z", "event":"CodexEntry", "EntryID":2207001, "Name":"$Codex_Ent_S_Seed_SdTp07_Def_Name;", "Name_Localised":"Candidum Rhizome Pod", "SubCategory":"$Codex_SubCategory_Organic_Structures;", "SubCategory_Localised":"Organic structures", "Category":"$Codex_Category_Biology;", "Category_Localised":"Biological and Geological", "Region":"$Codex_RegionName_39;", "Region_Localised":"Tenebrae", "System":"Swauwry UY-S d3-5", "SystemAddress":190127804067, "BodyID":18, "NearestDestination":"$Fixed_Event_Life_Ring;", "NearestDestination_Localised":"Notable stellar phenomena", "IsNewEntry":true }
{ "timestamp":"2024-03-11T01:15:36Z", "event":"CodexEntry", "EntryID":2207001, "Name":"$Codex_Ent_S_Seed_SdTp07_Def_Name;", "Name_Localised":"Candidum Rhizome Pod", "SubCategory":"$Codex_SubCategory_Organic_Structures;", "SubCategory_Localised":"Organic structures", "Category":"$Codex_Category_Biology;", "Category_Localised":"Biological and Geological", "Region":"$Codex_RegionName_39;", "Region_Localised":"Tenebrae", "System":"Swauwry UY-S d3-5", "SystemAddress":190127804067, "BodyID":18, "NearestDestination":"$Fixed_Event_Life_Ring;", "NearestDestination_Localised":"Notable stellar phenomena", "Traits":[ "s_s_cluster" ], "NewTraitsDiscovered":true }
```

**Comment by svensven** [comment]
Happens in 1.1.0.55 too

**Comment by njthomson** [comment]
Thank you @svensven for reporting this and for checking build `1.1.0.55` already.

**Comment by njthomson** [comment]
@svensven - this is fixed with this build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.57
