### ISSUE TITLE
FileNotFoundException "C:\WINDOWS\System32\images\alpha-background.png" at 9/27/2023 7:38:34 PM -06:00

### ISSUE THREAD

**Issue by Bi11T** [njthomson/SrvSurvey#8]
### What happened?

Clicked om maps

### Version

1.0.0.0

### Exception message

C:\WINDOWS\System32\images\alpha-background.png

### Exception stack

   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at SrvSurvey.FormRuins.loadMap(GuardianSiteData newSite)
   at SrvSurvey.FormRuins.loadMap(String name)
   at SrvSurvey.FormRuins.comboSite_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at SrvSurvey.FormRuins.showFilteredSites(GuardianSiteData siteData)
   at SrvSurvey.FormRuins..ctor(GuardianSiteData siteData)
   at SrvSurvey.FormRuins.show(GuardianSiteData siteData)
   at SrvSurvey.Main.btnRuins_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Contact Details

bill.thompsonn@gmail.com

### Relevant log output

```shell
19:37:10: Reading 1 ruins files from disk
19:37:10: Loaded data from: C:\Users\billt\AppData\Roaming\SrvSurvey\SrvSurvey\1.0.0.0\guardian\F9972008\Graea Hypue LO-P d6-194 14 b-ruins-1.json
19:37:10: Exception: C:\WINDOWS\System32\images\alpha-background.png
19:37:10: Inner exception: 
19:37:10: Stack:    at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at SrvSurvey.FormRuins.loadMap(GuardianSiteData newSite)
   at SrvSurvey.FormRuins.loadMap(String name)
   at SrvSurvey.FormRuins.comboSite_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at SrvSurvey.FormRuins.showFilteredSites(GuardianSiteData siteData)
   at SrvSurvey.FormRuins..ctor(GuardianSiteData siteData)
   at SrvSurvey.FormRuins.show(GuardianSiteData siteData)
   at SrvSurvey.Main.btnRuins_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
19:37:26: Searching journals for last touchdown location...
19:37:43: Searching journals for last touchdown location...
19:37:59: Searching journals for last touchdown location...
19:38:16: Searching journals for last touchdown location...
19:38:33: Searching journals for last touchdown location...
```

**Comment by njthomson** [comment]
Thank you @Bi11T for reporting this issue.

**Comment by njthomson** [comment]
@Bi11T - a fix is ready. Please try build `1.0.8.43` from [the latest build](https://github.com/njthomson/SrvSurvey/actions/runs/6335125220) and let me know if the problem still happens.
