### ISSUE TITLE
App would start

### ISSUE THREAD

**Issue by buzyperson** [njthomson/SrvSurvey#90]
### What happened?

I launched the app

### Version

I don't know

### Exception message

FileNotFoundException:Could not find file 'C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.2.0_x64__p4c193bsm1z5a\SrvSurvey\allBeacons.json'.

   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at SrvSurvey.canonn.Canonn.init(Boolean devReload)
   at SrvSurvey.Main.<Main_Load>b__9_2()

### Exception stack

FileNotFoundException:Could not find file 'C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.2.0_x64__p4c193bsm1z5a\SrvSurvey\allBeacons.json'.

   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at SrvSurvey.canonn.Canonn.init(Boolean devReload)
   at SrvSurvey.Main.<Main_Load>b__9_2()

### Relevant log output

```shell
FileNotFoundException:Could not find file 'C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.2.0_x64__p4c193bsm1z5a\SrvSurvey\allBeacons.json'.

   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at SrvSurvey.canonn.Canonn.init(Boolean devReload)
   at SrvSurvey.Main.<Main_Load>b__9_2()
```

**Comment by njthomson** [comment]
Thank you @buzyperson for reporting this. For a rough version - how recently did you install SrvSurvey?

And, if you restart SrvSurvey a few times, does it have this problem every time?

**Comment by buzyperson** [comment]
It's a recent install from the Microsoft store.  Maybe a week or so ago.    The blocker happens 100% of the time today. 

Here's the logs from just now: 
19:55:56: SrvSurvey version: 1.1.2.0
19:55:56: New log file: C:\Users\buzyp\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240404_195556.txt
19:55:56: dataFolder: C:\Users\buzyp\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0
19:55:56: Removing old log file: C:\Users\buzyp\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240331_064936.txt
19:55:56: Loaded settings: {
  "preferredCommander": null,
  "lastCommander": "fcsuper",
  "lastFid": "F3956008",
  "watchedJournalFolder": "C:\\Users\\buzyp\\Saved Games\\Frontier Developments\\Elite Dangerous\\",
  "hideJournalWriteTimer": false,
  "targetLatLong": {
    "lat": 0.0,
    "long": 0.0
  },
  "targetLatLongActive": false,
  "autoShowBioSummary": true,
  "autoShowBioPlot": true,
  "autoShowPlotFSS": true,
  "autoShowGuardianSummary": true,
  "autoShowRamTah": true,
  "autoShowPlotSysStatus": true,
  "skipGasGiantDSS": true,
  "skipRingsDSS": false,
  "skipLowValueDSS": true,
  "skipLowValueAmount": 1000000,
  "skipHighDistanceDSS": false,
  "skipHighDistanceDSSValue": 100000,
  "autoTrackCompBioScans": true,
  "skipAnalyzedCompBioScans": true,
  "autoRemoveTrackerOnSampling": true,
  "useExternalData": true,
  "autoLoadPriorScans": true,
  "skipPriorScansLowValue": false,
  "skipPriorScansLowValueAmount": 1000000,
  "showCanonnSignalsOnRadar": true,
  "useSmallCirclesWithCanonn": true,
  "hideMyOwnCanonnSignals": true,
  "focusGameOnStart": true,
  "focusGameOnMinimize": true,
  "enableGuardianSites": true,
  "disableRuinsMeasurementGrid": false,
  "disableAerialAlignmentGrid": false,
  "hidePlottersFromCombatSuits": true,
  "hideOverlaysFromMouse": true,
  "autoShowFlightWarnings": true,
  "highGravityWarningLevel": 1.0,
  "plotterOpacity": 50.0,
  "plotterScale": 0.0,
  "formMainLocation": "-525, 17",
  "formLogsLocation": "0, 0, 0, 0",
  "formAllRuinsLocation": "0, 0, 0, 0",
  "formRuinsLocation": "0, 0, 0, 0",
  "formBeaconsLocation": "0, 0, 0, 0",
  "formMapEditor": "0, 0, 0, 0",
  "formRamTah": "0, 0, 0, 0",
  "mapShowNotes": true,
  "blinkTigger": 134217728,
  "blinkDuration": 3000,
  "processScreenshots": false,
  "addBannerToScreenshots": true,
  "deleteScreenshotOriginal": false,
  "useGuardianAerialScreenshotsFolder": true,
  "screenshotSourceFolder": "D:\\Pictures\\Frontier Developments\\Elite Dangerous",
  "screenshotTargetFolder": "D:\\Pictures\\Frontier Developments\\Elite Dangerous\\converted",
  "rotateAndTruncateAlphaAerialScreenshots": true,
  "screenshotBannerColor": "Yellow",
  "screenshotBannerLocalTime": false,
  "aerialAltAlpha": 1200.0,
  "aerialAltBeta": 1550.0,
  "aerialAltGamma": 1600.0,
  "idxGuardianPlotter": 0,
  "migratedAlphaSiteHeading": false,
  "inferColor": "102, 255, 255",
  "inferTolerance": 25,
  "inferThreshold": 0.002,
  "dataFolder1100": true,
  "pubCodexRef": 2,
  "pubDataSettlementTemplate": 25,
  "pubDataGuardian": 25,
  "processIdx": 0
}
19:55:56: Reading PlotterPositions from: C:\Users\buzyp\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\plotters.json
19:55:56: Program.repositionPlotters: 0, rect{X=0,Y=0,Width=0,Height=0}
19:55:56: Watching folder: C:\Users\buzyp\Saved Games\Frontier Developments\Elite Dangerous\
19:55:56: Watching file: C:\Users\buzyp\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
19:55:57: isMigrationValid: False, dataFolder1100: True
19:55:57: Using settlementTemplates.json from pubData
19:55:57: Reading settlementTemplates.json: C:\Users\buzyp\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
19:55:57: SiteTemplate.Imported 13 templates
19:55:57: updatePubData ...
19:55:57: pubDataSettlementTemplate - local: 25, remote: 25
19:55:57: pubDataGuardian - local: 25, remote: 25
19:55:57: updatePubData - complete
19:55:57: System.IO.FileNotFoundException: Could not find file 'C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.2.0_x64__p4c193bsm1z5a\SrvSurvey\allBeacons.json'.
File name: 'C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.2.0_x64__p4c193bsm1z5a\SrvSurvey\allBeacons.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at SrvSurvey.canonn.Canonn.init(Boolean devReload)
   at SrvSurvey.Main.<Main_Load>b__9_2()
19:55:57: isFirewallProblem?
System.IO.FileNotFoundException: Could not find file 'C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.2.0_x64__p4c193bsm1z5a\SrvSurvey\allBeacons.json'.
File name: 'C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.2.0_x64__p4c193bsm1z5a\SrvSurvey\allBeacons.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at SrvSurvey.canonn.Canonn.init(Boolean devReload)
   at SrvSurvey.Main.<Main_Load>b__9_2()
19:56:04: Opening link: (length: 45)
https://github.com/njthomson/SrvSurvey/issues

**Comment by njthomson** [comment]
This is a very odd predicament.

I published version 1.1.3.0 recently, could you try updating to that? (Without un-installing the current version that is)

**Comment by buzyperson** [comment]
According the MS Store, I have the lastest, 1.1.3.0  It doesn't have the upgrade button.  The logs of course still say 1.1.2.0

**Comment by buzyperson** [comment]
Is it possible there are multiple installed versions that are conflicting?  (Though that didn't happen until today)

**Comment by njthomson** [comment]
I didn't think that was possible. Microsoft controls App store installs very tightly. It's as if Windows auto-updated the version for you, but it's still trying to use some files from the old version.

I'm curious if you have this folder on your system?
`C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.3.0_x64__p4c193bsm1z5a\SrvSurvey`

**Comment by njthomson** [comment]
I'm also curious if you have a folder `"%appdata%\SrvSurvey\SrvSurvey\1.1.0.0\"`

**Comment by buzyperson** [comment]
Yeah, I just found that from the logs.  I'm using a desktop shortcut (so I don't have to drill down into the Start Menu all the time).  The folder was still pointing to 142860789C73F_1.1.2.0_x64__p4c193bsm1z5a, which actually still exists on my system for whatever reason.  I pointed my shortcut to the new location, and the issue is gone.

**Comment by njthomson** [comment]
Glad we got to the bottom of it.

Thank you for using SrvSurvey :)

**Comment by buzyperson** [comment]
Should I delete the old folder for 1.1.2.0?

**Comment by njthomson** [comment]
You could wait and see if the next build does it automatically, otherwise yes.
