### ISSUE TITLE
TargetInvocationException "Exception has been thrown by the target of an invocation." at 13/04/2024 07:58:06 +01:00

### ISSUE THREAD

**Issue by brammmers** [njthomson/SrvSurvey#95]
### What happened?

toggled the galmap overlay on/off and saved settings

### Version

1.1.3.11

### Exception message

Exception has been thrown by the target of an invocation.

### Exception stack

   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SrvSurvey.Program.showPlotter[T]() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 133
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 310
   at SrvSurvey.Main.btnSettings_Click(Object sender, EventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 1060
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1802","build":"r301217/r0 ","timestamp":"2024-04-13T06:12:23Z","event":"Fileheader"}
07:53:50: Getting system bodies by name: Col 285 Sector SI-I a39-1
07:53:50: Game.event => FSDTarget
07:53:53: Game.event => NavRoute
07:53:53: Getting system bodies by name: Col 285 Sector WR-P b20-0
07:53:53: Game.event => FSDTarget
07:54:00: Game.event => NavRoute
07:54:00: Getting system bodies by name: Skil'sla
07:54:00: Getting system bodies by name: Upaniklis
07:54:00: Game.event => FSDTarget
07:55:30: Game.event => NavRoute
07:55:30: Getting system bodies by name: Orobu
07:55:30: Game.event => FSDTarget
07:57:27: Program.CloseAllPlotters
07:57:27: Program.Closing plotter: PlotBioStatus
07:57:27: Program.Closing plotter: PlotGalMap
07:57:27: Program.Closing plotter: PlotBioSystem
07:57:27: Program.Creating plotter: PlotGalMap
07:57:27: Exception: Exception has been thrown by the target of an invocation.
07:57:27: Inner exception: Parameter is not valid.
07:57:27: Stack:    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SrvSurvey.Program.showPlotter[T]() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Program.cs:line 133
   at SrvSurvey.Main.updateAllControls(Nullable`1 newMode) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 310
   at SrvSurvey.Main.btnSettings_Click(Object sender, EventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 1060
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by njthomson** [comment]
Fix is ready for next build.

**Comment by njthomson** [comment]
A better fix will be ready soon.

**Comment by njthomson** [comment]
This has been fixed in recent builds.
