### ISSUE TITLE
IOException "The process cannot access the file 'C:\Users\juana\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\settings.json' because it is being used by another process." at 17/04/2024 0:19:53 +02:00

### ISSUE THREAD

**Issue by verdecima** [njthomson/SrvSurvey#96]
### What happened?

i have ediscovert those star systems and i have mase the first step on it

### Version

1.1.0.44

### Exception message

The process cannot access the file 'C:\Users\juana\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\settings.json' because it is being used by another process.

### Exception stack

   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at SrvSurvey.Settings.Save()
   at SrvSurvey.Main.Main_FormClosed(Object sender, FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Relevant log output

```shell
23:45:18: Mode change Landed => ExternalPanel
23:45:18: Program.Creating plotter: PlotSysStatus
23:45:18: Program.Showing plotter: PlotSysStatus
23:47:02: Mode change ExternalPanel => Landed
23:47:02: Program.Closing plotter: PlotSysStatus
23:47:24: Game.event => Music
23:47:24: Mode change Landed => MainMenu
23:47:34: Game.event => Shutdown
23:47:34: Mode change MainMenu => Offline
23:47:34: Failed on attempt 1 to save: C:\Users\juana\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\systems\F4687379\Dryo Aowsy ML-P d5-160_5511223185587.json
23:47:34: Main.Shutdown: Commander:Verdecima
23:47:34: Main.removeGame, has old game: True
23:47:34: Program.CloseAllPlotters
23:47:34: Program.Closing plotter: PlotPulse
23:50:10: Saving settings on close...
23:50:10: Exception: The process cannot access the file 'C:\Users\juana\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\settings.json' because it is being used by another process.
23:50:10: Inner exception: 
23:50:10: Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at SrvSurvey.Settings.Save()
   at SrvSurvey.Main.Main_FormClosed(Object sender, FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
00:04:36: Opening link: (length: 3760)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=IOException+%22The+process+cannot+access+the+file+%27C%3A%5CUsers%5Cjuana%5CAppData%5CRoaming%5CSrvSurvey%5CSrvSur

00:12:33: Opening link: (length: 4037)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=IOException+%22The+process+cannot+access+the+file+%27C%3A%5CUsers%5Cjuana%5CAppData%5CRoaming%5CSrvSurvey%5CSrvSur
```

**Comment by verdecima** [comment]
i have discovert those star wsystems and i made the first step on those planets
