### ISSUE TITLE
IOException "The process cannot access the file 'C:\Users\juana\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\settings.json' because it is being used by another process." at 19/04/2024 8:22:03 +02:00

### ISSUE THREAD

**Issue by verdecima** [njthomson/SrvSurvey#99]
### What happened?

COMANDER verdecima your program has failed again you schould solve this situation

### Version

1.1.0.44

### Exception message

The process cannot access the file 'C:\Users\juana\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\settings.json' because it is being used by another process.

### Exception stack

   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at SrvSurvey.Settings.Save()
   at SrvSurvey.Main.Main_FormClosed(Object sender, FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by njthomson** [comment]
Thank you @verdecima for reporting this. Does this problem happen consistently?

Is it possible you had 2 copies of SrvSurvey running at the same time?

**Comment by verdecima** [comment]
It happens constantly

**Comment by njthomson** [comment]
Can you try rebooting and see if the problem still occurs?

You could also try a newer build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.11

Regardless, I will add an error handler and retry mechanism where this error is occuring.

**Comment by njthomson** [comment]
Fix has been checked in.

**Comment by njthomson** [comment]
Fix is available in build `1.1.3.30`:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.30
